### ISSUE TITLE
Error in installing 5.3.3 : ext/intl/grapheme_string.o

### ISSUE THREAD

**Issue by crysaro** [phpbrew/phpbrew#788] opened 2016-09-09 10:14 UTC
### Output

Error: Make failed:
The last 5 lines in the log file:
ext/intl/grapheme/grapheme_string.o:(.rodata+0x8): undefined reference to `grapheme_extract_bytecount_iter'

ext/intl/grapheme/grapheme_string.o:(.rodata+0x10): undefined reference to `grapheme_extract_charcount_iter'

collect2: error: ld returned 1 exit status

Makefile:246: recipe for target 'sapi/cgi/php-cgi' failed

make: **\* [sapi/cgi/php-cgi] Error 1
### Command

   phpbrew --debug install 5.3.3 +default +mysql
### Build Log

[phpbrew-build-log.txt](https://github.com/phpbrew/phpbrew/files/463736/phpbrew-build-log.txt)
### Platform

OS:

   Ubuntu 16.04

Running PHP: 7.0.8

Installing PHP: 5.3.3

**Comment by jhdxr** [comment] 2016-09-09 14:49
try `sudo apt-get install libicu-dev`
and if you do not need intl support, you can disable it by `phpbrew install XXXX --disable-intl`

**Comment by crysaro** [comment] 2016-09-13 04:01
I tried:

try sudo apt-get install libicu-dev

I got:

libicu-dev is already the newest version (55.1-7).
libicu-dev set to manually installed.
The following packages were automatically installed and are no longer required:
  dbconfig-common dbconfig-mysql libjs-sphinxdoc linux-headers-4.4.0-31
  linux-headers-4.4.0-31-generic linux-image-4.4.0-31-generic
  linux-image-extra-4.4.0-31-generic linux-signed-image-4.4.0-31-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.


When I did:

phpbrew install 5.3.3 +default +mysql --  --disable-intl

I got:

libtool: unrecognized option `-export-dynamic'

Try `libtool --help' for more information.

Makefile:245: recipe for target 'sapi/cgi/php-cgi' failed

make: *** [sapi/cgi/php-cgi] Error 1

I looked it up and found https://github.com/phpbrew/phpbrew/issues/83

but then I got the original error:

Error: Make failed:
The last 5 lines in the log file:
ext/intl/grapheme/grapheme_string.o:(.rodata+0x8): undefined reference to `grapheme_extract_bytecount_iter'

ext/intl/grapheme/grapheme_string.o:(.rodata+0x10): undefined reference to `grapheme_extract_charcount_iter'

collect2: error: ld returned 1 exit status

Makefile:246: recipe for target 'sapi/cgi/php-cgi' failed

make: *** [sapi/cgi/php-cgi] Error 1

**Comment by alcaitiff** [comment] 2016-11-10 18:23
I'm getting same problem here. Did you solved it?

**Comment by jwhayman** [comment] 2017-08-30 15:19
I got it working by applying [this patch](https://bugs.php.net/patch-display.php?bug_id=55019&patch=intl-fixes&revision=latest).

**Comment by peter279k** [comment] 2022-12-02 08:18
The issue is resolved in the previous reply and closed now.

**Closed by peter279k** 2022-12-02 08:18 UTC
Labels: Extension Installer
