### ISSUE TITLE
"Download failed." even if the file is successfully downloaded.

### ISSUE THREAD

**Issue by kherge** [phpbrew/phpbrew#443] opened 2014-12-31 21:23 UTC
Regardless of what I'm downloading, I see the error "Download failed."

# Extensions

## First Run

```
===> Downloading from http://pecl.php.net/get/APC-3.1.13.tgz
--2014-12-31 13:02:46--  http://pecl.php.net/get/APC-3.1.13.tgz
Resolving pecl.php.net (pecl.php.net)... 76.75.200.106
Connecting to pecl.php.net (pecl.php.net)|76.75.200.106|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 171591 (168K) [application/octet-stream]
Saving to: ‘/home/kherrera/.phpbrew/distfiles/APC-3.1.13.tgz’

100%[=======================================================================================================================================================================================================================>] 171,591      154KB/s   in 1.1s   

2014-12-31 13:02:47 (154 KB/s) - ‘/home/kherrera/.phpbrew/distfiles/APC-3.1.13.tgz’ saved [171591/171591]

Download failed.
```

## Second Run

```
===> Downloading from http://pecl.php.net/get/APC-3.1.13.tgz
--2014-12-31 13:22:07--  http://pecl.php.net/get/APC-3.1.13.tgz
Resolving pecl.php.net (pecl.php.net)... 76.75.200.106
Connecting to pecl.php.net (pecl.php.net)|76.75.200.106|:80... connected.
HTTP request sent, awaiting response... 200 OK

    The file is already fully retrieved; nothing to do.

Download failed.
```

# Builds

## First Run

```
===> phpbrew will now build 5.6.4
===> Loading and resolving variants...
===> Downloading from http://www.php.net/get/php-5.6.4.tar.bz2/from/this/mirror
--2014-12-31 13:09:41--  http://www.php.net/get/php-5.6.4.tar.bz2/from/this/mirror
Resolving www.php.net (www.php.net)... 72.52.91.14, 2001:470:1:380::3
Connecting to www.php.net (www.php.net)|72.52.91.14|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://php.net/get/php-5.6.4.tar.bz2/from/this/mirror [following]
--2014-12-31 13:09:42--  http://php.net/get/php-5.6.4.tar.bz2/from/this/mirror
Resolving php.net (php.net)... 72.52.91.14, 2001:470:1:380::3
Reusing existing connection to www.php.net:80.
HTTP request sent, awaiting response... 302 Found
Location: http://php.net/distributions/php-5.6.4.tar.bz2 [following]
--2014-12-31 13:09:42--  http://php.net/distributions/php-5.6.4.tar.bz2
Reusing existing connection to www.php.net:80.
HTTP request sent, awaiting response... 200 OK
Length: 13498882 (13M) [application/octet-stream]
Saving to: ‘/home/kherrera/.phpbrew/distfiles/php-5.6.4.tar.bz2’

100%[=======================================================================================================================================================================================================================>] 13,498,882   352KB/s   in 31s    

2014-12-31 13:10:13 (424 KB/s) - ‘/home/kherrera/.phpbrew/distfiles/php-5.6.4.tar.bz2’ saved [13498882/13498882]

Download failed.
```

## Second Run

Forgot to copy and paste the result, but it was successful.

# Information

Here are the permissions for the `.phpbrew` directory:

```
├── [drwxr-xr-x kherrera kherrera]  .phpbrew
│   ├── [-rw-rw-r-- kherrera kherrera]  bashrc
│   ├── [drwxrwxr-x kherrera kherrera]  bin
│   ├── [drwxr-xr-x kherrera kherrera]  build
│   ├── [drwxr-xr-x kherrera kherrera]  distfiles
│   ├── [-rw-rw-r-- kherrera kherrera]  .metadata_never_index
│   ├── [drwxr-xr-x kherrera kherrera]  php
│   ├── [-rw-rw-r-- kherrera kherrera]  phpbrew.fish
│   ├── [-rw-rw-r-- kherrera kherrera]  php-releases.json
│   ├── [drwxr-xr-x kherrera kherrera]  tmp
│   └── [drwxr-xr-x kherrera kherrera]  variants
```

Here is the contents of `.phpbrew/distfiles`:

```
[vm-cin02: kherrera] 13:14:29 distfiles $ pwd
/home/kherrera/.phpbrew/distfiles
[vm-cin02: kherrera] 13:14:30 distfiles $ tree
.
├── APC-3.1.13.tgz
└── php-5.6.4.tar.bz2

0 directories, 5 files
[vm-cin02: kherrera] 13:14:31 distfiles $ 
```

**Comment by marcioAlmada** [comment] 2015-01-01 00:08
Tried everything here:

- installed a new PHP
- installed some PECL extensions
- installed from mirror link

Found no issue. Could you try some of the available [mirrors](http://php.net/mirrors.php) and report back?

**Comment by kherge** [comment] 2015-01-01 00:53
I'm sorry, but I'm not sure what difference that would make.

The packages are successfully downloaded, which tells me that the mirror is just fine. It looks like the [fault lies here](https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/Downloader/UrlDownloader.php#L71) since [this line](https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/Downloader/UrlDownloader.php#L74) never seems to be called (note that it's not in my output).

**Comment by marcioAlmada** [comment] 2015-01-01 01:09
Yeah, that's right, sorry. Humm... but why would `file_exists()` be false in your case? Your file permissions seems ok.

We could try to [`clearstatcache()`](http://php.net/manual/pt_BR/function.clearstatcache.php) before assert file existence, though,  for now, I think it might be an isolated issue.

**Comment by shinnya** [comment] 2015-01-01 07:38
@kherge @marcioAlmada I've found the root cause of this issue and fixed in https://github.com/phpbrew/phpbrew/pull/444 .

**Comment by c9s** [comment] 2015-01-01 11:27
Looks like fixed by @shinnya++

**Comment by c9s** [comment] 2015-01-01 11:29
Please try and verify the issue on 1.18.4 release https://github.com/phpbrew/phpbrew/releases/tag/1.18.4

**Comment by marcioAlmada** [comment] 2015-01-01 21:36
@c9s @shinnya thanks, that was very unexpected.

Happy new year! :)

**Comment by c9s** [comment] 2015-01-02 09:17
Happy new year!

**Comment by shinnya** [comment] 2015-01-02 09:41
Happy new year, all!

**Comment by kherge** [comment] 2015-01-03 17:21
Thanks for the PR and new release!

I'll try it out when I get back to work on Monday.

**Comment by kherge** [comment] 2015-01-09 21:03
Oddly enough, I can't repeat the issue anymore using the version of the app.

I don't know whether I should leave this open or close it.

**Comment by marcioAlmada** [comment] 2015-01-09 21:30
Let's close, and reopen in case more information appears.

**Closed by marcioAlmada** 2015-01-09 21:30 UTC
Labels: Need More Info
