### ISSUE TITLE
error: incomplete definition of type 'struct php_mb_re_pattern_buffer'

### ISSUE THREAD

**Issue by donotor** [phpbrew/phpbrew#1184] opened 2020-06-01 18:27 UTC
### Output

```
error: incomplete definition of type 'struct php_mb_re_pattern_buffer'
```

### Expected Result

```
build OK
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

phpbrew --debug install 5.6.40 +default +pdo +gd +mysql +apxs2=/usr/local/opt/httpd/bin/apxs +zlib="$(brew --prefix zlib)"  -- --with-libedit=$(brew --prefix libedit)

The error came out after i added the "+gd" option to the command. Before that, it worked ok.
Using phpbrew 1.26.0

### Build Log

    https://gist.github.com/donotor/5dfaf5b02764343a676aa6b199851b6d

### Platform

OS: OS X 10.15.4

Running PHP: PHP 7.4.4 (cli) (built: Mar 19 2020 20:12:27) ( NTS )

Installing PHP: 5.6.40

**Comment by peter279k** [comment] 2022-12-01 10:42
It's related to the issue https://github.com/phpbrew/phpbrew/issues/1003.

**Comment by peter279k** [comment] 2022-12-05 10:15
I use the above running commands on the `macOS 12.6` and some command outputs are as follows:

```bash
cloudxmac@Mac-5 ~ % export CFLAGS="-Wno-implicit-function-declaration"
cloudxmac@Mac-5 ~ % brew install libedit
cloudxmac@Mac-5 ~ % phpbrew install 5.6 +default +zlib="$(brew --prefix zlib)" -- --with-libedit="$(brew --prefix libedit)" --with-openssl="$(brew --prefix openssl@1.1)"
......
===> Building...
Build finished: 4 minutes.
Installing..
Congratulations! Now you have PHP with 5.6.40 as php-5.6.40

* To configure your installed PHP further, you can edit the config file at
    /Users/cloudxmac/.phpbrew/php/php-5.6.40/etc/php.ini

To use the newly built PHP, try the line(s) below:

    $ phpbrew use php-5.6.40

Or you can use switch command to switch your default php to php-5.6.40:

    $ phpbrew switch php-5.6.40

Enjoy!
cloudxmac@Mac-5 ~ %
```

I'm going to close the issue because I cannot reproduce that.

**Closed by peter279k** 2022-12-05 10:15 UTC
Labels: macOS
