### ISSUE TITLE
Install IMAP extension for php7.0.6

### ISSUE THREAD

**Issue by rkovalyov** [phpbrew/phpbrew#749] opened 2016-06-11 13:27 UTC
`phpbrew ext install imap`
### Output

===> Installing imap extension...
Log stored at: /root/.phpbrew/build/php-7.0.6/ext/imap/build.log
Changing directory to /root/.phpbrew/build/php-7.0.6/ext/imap
===> Phpize...
===> Configuring...
Error: Command failed: ./configure --with-php-config=/root/.phpbrew/php/php-7.0.6/bin/php-config >> /root/.phpbrew/build/php-7.0.6/ext/imap/build.log 2>&1 returns:
PHP Notice:  Undefined variable: configureOptions in phar:///usr/bin/phpbrew/src/PhpBrew/Console.php on line 131
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpbrew:0
PHP   2. require() /usr/bin/phpbrew:99
PHP   3. PhpBrew\Console->runWithTry() phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php:2

Notice: Undefined variable: configureOptions in phar:///usr/bin/phpbrew/src/PhpBrew/Console.php on line 131

Call Stack:
    0.0009     383136   1. {main}() /usr/bin/phpbrew:0
    0.0255     924088   2. require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php') /usr/bin/phpbrew:99
    0.0367    1455968   3. PhpBrew\Console->runWithTry() phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php:2

PHP Warning:  implode(): Invalid arguments passed in phar:///usr/bin/phpbrew/src/PhpBrew/Console.php on line 131
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpbrew:0
PHP   2. require() /usr/bin/phpbrew:99
PHP   3. PhpBrew\Console->runWithTry() phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php:2
PHP   4. implode() phar:///usr/bin/phpbrew/src/PhpBrew/Console.php:131

Warning: implode(): Invalid arguments passed in phar:///usr/bin/phpbrew/src/PhpBrew/Console.php on line 131

Call Stack:
    0.0009     383136   1. {main}() /usr/bin/phpbrew:0
    0.0255     924088   2. require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php') /usr/bin/phpbrew:99
    0.0367    1455968   3. PhpBrew\Console->runWithTry() phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php:2
    1.9300    4319056   4. implode() phar:///usr/bin/phpbrew/src/PhpBrew/Console.php:131
### Command

```
phpbrew ext install imap
```
### Platform

OS: Ubuntu 14.04

Running PHP: 7.0.6, 7.0.7

Installing PHP: 7.0.6, 7.07
phpbrew: 1.21.6

**Comment by c9s** [comment] 2016-06-12 13:56
Be sure to add `--with-kerberos` option

**Comment by c9s** [comment] 2016-06-12 13:56
the undefined variable issue was fixed

**Comment by qakovalyov** [comment] 2016-06-12 14:36
I have tried run ```phpbrew ext install --with-kerberos imap``` and got 

```GetOptionKit\Exception\InvalidOptionException: Invalid option: --with-kerberos```

**Comment by qakovalyov** [comment] 2016-06-12 14:37
And if without ```--with-kerberos``` option : 
```
Downloading https://pecl.php.net/rest/r/imap/stable.txt via curl extension
CurlKit\CurlException: (22) The requested URL returned error: 404 Not Found at [https://pecl.php.net/rest/r/imap/stable.txt:The requested URL returned error: 404 Not Found]
```

**Comment by c9s** [comment] 2016-06-12 15:42
The current command is:

    phpbrew --debug ext install  imap -- --with-kerberos

And please make sure you've installed one PHP and switch version to that PHP.

**Comment by c9s** [comment] 2016-06-12 15:55
Not sure why you don't have imap, is it from pecl or built-in in php distribution ?

Can you check {BUILD_DIR}/ext/imap ?

**Comment by qakovalyov** [comment] 2016-06-12 15:59
folder does not exist

**Comment by Gasol** [comment] 2016-06-13 06:21
@qakovalyov 

If folder does exists, Try reinstall php-7.0.6, Check {BUILD_DIR}/ext/imap again. Make sure you have right permission to access {BUILD_DIR}/ext/imap, That's why you are trying to access PECL site to get imap distribution.

If you are building imap extension in Ubuntu, Make sure you installed libc-client2007e before installing imap extension.

**Comment by qakovalyov** [comment] 2016-06-13 09:54
1. ```libc-client2007e``` already installed.
2. Reinstall latest php ```phpbrew install 7.0 +everything``` 
3. Same Behavior. {BUILD_DIR}/ext/imap doesn't exist and I cannot install ```ext imap```

**Comment by qakovalyov** [comment] 2016-06-13 10:01
but for ```php5```  ```imap``` successfully installed

**Comment by chippyash** [comment] 2016-06-29 14:06
I can confirm the problem. Exactly the same for me.
```
phpbrew ext install imap -- --with-kerberos
===> Installing imap extension...
Log stored at: /home/name/.phpbrew/build/php-7.0.0/ext/imap/build.log
Changing directory to /home/name/.phpbrew/build/php-7.0.0/ext/imap
Makefile not found
===> Phpize...
===> Configuring...
Command failed: ./configure '--with-kerberos' --with-php-config=/home/name/.phpbrew/php/php-7.0.0/bin/php-config >> /home/name/.phpbrew/build/php-7.0.0/ext/imap/build.log 2>&1 returns 
```
libc-client2007e-dev is installed (this is an ubuntu based machine)

**Comment by umbri** [comment] 2016-07-21 01:41
Try this:
`phpbrew ext install imap -- --with-kerberos --with-imap-ssl`

**Comment by chippyash** [comment] 2016-07-21 07:31
@umbri - worked a treat - many thanks.

**Comment by morozov** [comment] 2017-09-29 19:47
Installing as `phpbrew ext install imap -- --with-kerberos --with-imap-ssl` works for me too. Closing the issue.

Added a note to [wiki](https://github.com/phpbrew/phpbrew/wiki/Cookbook/_edit#how-to-install-the-imap-extension).

**Closed by morozov** 2017-09-29 19:47 UTC
Labels: Support

**Comment by chippyash** [comment] 2017-09-29 20:07
This dangers into dependency management.  BUT. If the only way to install imap in phpbrew is with the extra flags, then phpbrew "should know that".  Else I suspect that these types of issues will re-occur

**Comment by morozov** [comment] 2017-09-29 20:36
@chippyash, according to the [PHP manual](http://php.net/manual/en/imap.installation.php):

> Depending on how the c-client was configured, you might also need to add **--with-imap-ssl=/path/to/openssl/** and/or **--with-kerberos=/path/to/kerberos** to the PHP configure line.

So it's not the only way. If PHPBrew could analyze the c-client configuration and provide the needed flags accordingly, it indeed would be nice. But right now, the only way to determine the flags is the way of trial and error.

**Comment by chippyash** [comment] 2017-09-29 21:08
@morozov yup. You have it. Phpbrew needs to do that. Exactly.  Although I have been using phpbrew for many years and thank the contributors many times over, it is exactly this type of consideration that would make phpbrew ubiquitous like composer.

**Comment by morozov** [comment] 2017-09-29 21:14
@chippyash I totally agree with you. Feel free to file another ticket. This one is about not being able to install the extension which is resolved and documented.

**Comment by chippyash** [comment] 2017-10-06 21:32
@morozov https://github.com/phpbrew/phpbrew/issues/914  If I haven't stated it clearly enough, please feel free to add

**Comment by roman-1983** [comment] 2018-08-23 01:33
It could be that the kerberos-files are missing.
*For ubuntu*
`apt install libkrb5-dev`
