### ISSUE TITLE
What "please provide an address to listen on as the first argument" ?

### ISSUE THREAD

**Issue by yiranzai** [phpbrew/phpbrew#1203] opened 2020-10-30 16:44 UTC
### Output

```
phpbrew install 7.3 +default +gd +bz2=/usr/local/opt/bzip2 +zlib=/usr/local/opt/zlib +iconv="$(brew --prefix libiconv)" +gd +pdo +mysql +sqlite +debug +fpm -- --with-openssl=/usr/local/opt/openssl --with-gd=shared --with-zlib-dir="$(brew --prefix zlib)"
Warning! The usage of PHP older than 7.2.0 as the interpreter is deprecated.
Please set the system interpreter using 'phpbrew system <version>'.
See https://github.com/phpbrew/phpbrew/wiki/System-Interpreter for details.
===> phpbrew will now build 7.3.24
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 55b7afbb2037b0f8fefc481a85f8df4f7a278b4b7f0ed9f674c50ec389cca598
===> Distribution file was successfully extracted, skipping...
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/Users/yiranzai/.phpbrew/build/php-7.3.24' --quiet 'clean'
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Checking patch for replace freetype-config with pkg-config on php older than 7.4
---> Applying patch...
patching file ext/gd/config.m4
Reversed (or previously applied) patch detected!  Skipping patch.
patch unexpectedly ends in middle of line
2 out of 2 hunks ignored -- saving rejects to file ext/gd/config.m4.rej

Patch failed
0 changes patched.
Found existing build.log, renaming it to /Users/yiranzai/.phpbrew/build/php-7.3.24/build.log.1604075183
===> Configuring 7.3.24...


Use tail command to see what's going on:
   $ tail -F '/Users/yiranzai/.phpbrew/build/php-7.3.24/build.log'


===> Checking patches...
Checking patch for php5.3.29 multi-sapi
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
6 changes patched.
Checking patch for php5.6 with openssl 1.1.x patch.
===> Building...
Error: Make failed:
The last 5 lines in the log file:
invertedregexiterator.inc

pharcommand.inc

phar.inc

please provide an address to listen on as the first argument

make: *** [all] Error 1

Please checkout the build log file for more details:
	 tail /Users/yiranzai/.phpbrew/build/php-7.3.24/build.log
```

### Expected Result

```
invertedregexiterator.inc

pharcommand.inc

phar.inc

please provide an address to listen on as the first argument

make: *** [all] Error 1
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

```
phpbrew install 7.3 +default +gd +bz2=/usr/local/opt/bzip2 +zlib=/usr/local/opt/zlib +iconv="$(brew --prefix libiconv)" +gd +pdo +mysql +sqlite +debug +fpm -- --with-openssl=/usr/local/opt/openssl --with-gd=shared --with-zlib-dir="$(brew --prefix zlib)"
```

```
phpbrew install 7.4 +default +openssl=/usr/local/Cellar/openssl/1.0.2p +sqlite +debug +gd +bz2="$(brew --prefix bzip2)" +zlib="$(brew --prefix zlib)" +iconv="$(brew --prefix libiconv)" +gd +pdo +mysql +fpm  -- --with-openssl=/usr/local/Cellar/openssl/1.0.2p --with-gd=shared --with-zlib-dir="$(brew --prefix zlib)"
```

### Build Log

https://gist.github.com/yiranzai/46b752134306a940f4693f20df25a70a

### Platform

OS:

    e.g. OS X 10.15.7

Running PHP: 7.1.33

Installing PHP: 7.3.24  7.4.12

**Comment by peter279k** [comment] 2022-12-05 10:35
I run the following commands on the `macOS 12.6` and some command outputs are as follows:

```bash
cloudxmac@Mac-5 ~ % sw_vers
ProductName:    macOS
ProductVersion: 12.6
BuildVersion:   21G115
cloudxmac@Mac-5 ~ %
cloudxmac@Mac-5 ~ % phpbrew install 7.3 +default +bz2=/usr/local/opt/bzip2 +zlib=/usr/local/opt/zlib -- --with-openssl=/usr/local/opt/openssl@1.1 --with-zlib-dir="$(brew --prefix zlib)"
......
Congratulations! Now you have PHP with 7.3.33 as php-7.3.33

* To configure your installed PHP further, you can edit the config file at
    /Users/cloudxmac/.phpbrew/php/php-7.3.33/etc/php.ini

To use the newly built PHP, try the line(s) below:

    $ phpbrew use php-7.3.33

Or you can use switch command to switch your default php to php-7.3.33:

    $ phpbrew switch php-7.3.33

Enjoy!
cloudxmac@Mac-5 ~ %
```

I'm going to close the issue because I cannot reproduce that.

**Closed by peter279k** 2022-12-05 10:35 UTC
Labels: Support, macOS
