### ISSUE TITLE
mac m1 fails to install phpbrew install 7.4.28 

### ISSUE THREAD

**Issue by FL-K** [phpbrew/phpbrew#1260] opened 2022-03-10 14:40 UTC
### Output

```
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.

Fatal error: Uncaught InvalidArgumentException: RegexIterator::__construct(): Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0 in /Users/kristi.jorgji/.phpbrew/build/php-7.4.28/ext/phar/phar.php:1133
Stack trace:
#0 /Users/kristi.jorgji/.phpbrew/build/php-7.4.28/ext/phar/phar.php(1133): RegexIterator->__construct(Object(RecursiveIteratorIterator), '/\\.svn/')
#1 /Users/kristi.jorgji/.phpbrew/build/php-7.4.28/ext/phar/phar.php(1077): PharCommand::phar_add(Object(Phar), 0, '/Users/kristi.j...', NULL, '/\\.svn/', Object(SplFileInfo), NULL, true)
#2 /Users/kristi.jorgji/.phpbrew/build/php-7.4.28/ext/phar/phar.php(225): PharCommand->cli_cmd_run_pack(Array)
#3 /Users/kristi.jorgji/.phpbrew/build/php-7.4.28/ext/phar/phar.php(2089): CLICommand->__construct(19, Array)
#4 {main}
  thrown in /Users/kristi.jorgji/.phpbrew/build/php-7.4.28/ext/phar/phar.php on line 1133
make: *** [ext/phar/phar.phar] Error 255
```

### Expected Result

Succeeds

### Command

```
OPENSSL_CFLAGS="-I/usr/local/opt/openssl@1.1/include" \
OPENSSL_LIBS="-L/usr/local/opt/openssl@1.1/lib -lcrypto -lssl" \
phpbrew install 7.4.28 +bz2="$(brew --prefix bzip2)"

```

### Platform

OS:

   macOs Monterey
  Chip: M1 Pro 2021

**Comment by alexwenzel** [comment] 2022-04-09 16:11
+1 

I have the same error.

**Comment by alexwenzel** [comment] 2022-04-09 16:20
I managed to install everythin with the following command:

```
phpbrew install 7.4 -- --without-pcre-jit
# or
phpbrew install 8.1.4 -- --without-pcre-jit

**Comment by peter279k** [comment] 2022-05-27 19:05
Hmm...I don't have the M1 Pro to reproduce the issue, but I think this issue is very similar with this [article](https://developpaper.com/mac-silicon-m1-compilation-and-installation-of-php8-swoole4-6-arm64/).

In above article, it seems that the same issues are as follows:

```
PHP Build ERROR: PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.
```

It seems that above exception can be ignored.

```
PHP Build ERROR: Allocation of JIT memory failed, PCRE JIT will be disabled. This is likely caused by security restrictions. Either grant PHP permission to allocate executable memory, or set pcre.jit=0
```

The above error is about the `pcre.jit` setting, and set the `ini_set("pcre.jit", "0");` in `/path/to/php-8.0.7/ext/phar/phar.php` or using this [solution](https://github.com/phpbrew/phpbrew/issues/1260#issuecomment-1094078081) is about ignore PCRE JIT.

**Comment by peter279k** [comment] 2022-12-05 04:17
I've one `macOS 11.6` and try to use the following steps to reproduce the issue:

```bash
bash-3.2$ OPENSSL_CFLAGS="-I/usr/local/opt/openssl@1.1/include" \
OPENSSL_LIBS="-L/usr/local/opt/openssl@1.1/lib -lcrypto -lssl" \
phpbrew install 7.4.28 +bz2="$(brew --prefix bzip2)"
......
Use tail command to see what's going on:
   $ tail -F '/Users/cloudxmac/.phpbrew/build/php-7.4.28/build.log'


===> Checking patches...
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
Checking patch for php5.6 with openssl 1.1.x patch.
===> Building...
......
* To configure your installed PHP further, you can edit the config file at
    /Users/cloudxmac/.phpbrew/php/php-7.4.28/etc/php.ini

To use the newly built PHP, try the line(s) below:

    $ phpbrew use php-7.4.28

Or you can use switch command to switch your default php to php-7.4.28:

    $ phpbrew switch php-7.4.28

Enjoy!
cloudxmac@cloudxmacs-Mac ~ % phpbrew use 7.4.28
cloudxmac@cloudxmacs-Mac ~ % php -v
PHP 7.4.28 (cli) (built: Dec  5 2022 12:12:20) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

I suspect the issue is only happened on the `macOS M1` version.

**Comment by peter279k** [comment] 2022-12-05 09:47
I've one `macOS 12.6`  and chip is the Intel x86_64 CPU. Then running the following steps to install the `PHP 7.4` version:

```bash
cloudxmac@Mac-5 ~ % sw_vers
ProductName:    macOS
ProductVersion: 12.6
BuildVersion:   21G115
cloudxmac@Mac-5 ~ % brew install bzip2 zlib openssl@1.1 oniguruma readline libzip libxml2 pkg-config
cloudxmac@Mac-5 ~ % OPENSSL_CFLAGS="-I/usr/local/opt/openssl@1.1/include" \
OPENSSL_LIBS="-L/usr/local/opt/openssl@1.1/lib -lcrypto -lssl" \
phpbrew install 7.4.28 +bz2="$(brew --prefix bzip2)"
......
Use tail command to see what's going on:
   $ tail -F '/Users/cloudxmac/.phpbrew/build/php-7.4.28/build.log'


===> Checking patches...
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
Checking patch for php5.6 with openssl 1.1.x patch.
===> Building...

* WARNING:
  You haven't setup your .bashrc file to load phpbrew shell script yet!
  Please run 'phpbrew init' to see the steps!

To use the newly built PHP, try the line(s) below:

    $ phpbrew use php-7.4.28

Or you can use switch command to switch your default php to php-7.4.28:

    $ phpbrew switch php-7.4.28

Enjoy!
cloudxmac@Mac-5 ~ %
```

I'm going to close the issue because I cannot reproduce that.

**Closed by peter279k** 2022-12-05 09:47 UTC
Labels: Support, macOS, PHP 7.4

**Comment by theofidry** [comment] 2022-12-05 22:38
@peter279k I can confirm this is purely about JIT. I can reproduce the original issue, the fix for me is:

```
$ phpbrew install --stdout 7.4.28 +bz2="$(brew --prefix bzip2)" +openssl="$(brew --prefix openssl@1.1)" -- --without-pcre-jit
```

**Comment by heidi-debo** [comment] 2022-12-21 11:52
@theofidry not sure that's true though. I had not issues compiling 8.1 and 8.2 on M1 myself. I had only issues with 8.0 although I admittedly didn't use `phpbrew` but `php-build`

**Comment by debo** [comment] 2022-12-21 12:49
@theofidry not sure that's true though. I had no issues compiling 8.1 and 8.2 on M1 myself. I had only issues with 8.0 although I admittedly didn't use phpbrew but php-build. Disabling PCRE JIT did the trick though so thank you all for this solution.

I recently found a better solution thanks to [this bug report](https://bugs.php.net/bug.php?id=80435). Instead of disabling PCRE JIT we can/should point the build to a more up to date pcre or pcre2 engine. The following commands should properly solve the issue without disabling PCRE JIT.

$ phpbrew install --stdout 7.4.28 +bz2="$(brew --prefix bzip2)" +openssl="$(brew --prefix openssl@1.1)" -- --with-external-pcre=$(brew --prefix pcre2)
Also, this shouldn't be needed for 8.1 and 8.2 but I suppose that if you are testing code across multiple versions of PHP it would be recommended to use the same regular expression engine so I would personally advise to recompile other versions accordingly.

I hope it helps.

**Comment by theofidry** [comment] 2022-12-21 15:36
awesome @debo thanks for the pointers!

It's been a recurrent point of pain for me tbh: the PHP compiler is really bad at telling you why this is broken, e.g. if you use the wrong openssl version you get a incompatible signature from a header file, instead of a clear message "version X picked up but require version Y"
