### ISSUE TITLE
PhpBrew connection timeout

### ISSUE THREAD

**Issue by Serginho** [phpbrew/phpbrew#726] opened 2016-05-06 14:29 UTC
### Output

phpbrew ext install xdebug  
Warning: Some extension won't be able to be built with php7. If the extension
supports php7 in another branch or new major version, you will need to specify
the branch name or version name explicitly.

For example, to install memcached extension for php7, use:

```
phpbrew ext install github:php-memcached-dev/php-memcached php7 -- --disable-memcached-sasl
```

CurlKit\CurlException: (28) Resolving timed out after 10524 milliseconds
Trace:

```
0) CurlKit\CurlDownloader->request('https://pecl.php.net/rest/r/xdebug/stable.txt')
1) PhpBrew\Extension\Provider\PeclProvider->getPackageXml('xdebug', 'stable')
2) PhpBrew\Extension\Provider\PeclProvider->buildPackageDownloadUrl('stable')
3) PhpBrew\Extension\ExtensionDownloader->download(PhpBrew\Extension\Provider\PeclProvider, 'stable')
4) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('xdebug')
5) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['xdebug'])
6) CLIFramework\CommandBase->executeWrapper(['xdebug'])
7) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'ext', 'install', 'xdebug'])
8) PhpBrew\Console->runWithTry(['/usr/local/bin/phpbrew', 'ext', 'install', 'xdebug'])
9) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')
```
### Expected Result

No exceptions
### Command

phpbrew ext install xdebug 
### Platform

OS:

```
 Ubuntu 14.04
```

Running PHP: 
 5.5.9 and 7.0.6

I don't know what happens with curl but, I don't have connectivity problems

**Comment by c9s** [comment] 2016-05-06 14:38
pecl site sometimes down?

Serginho <notifications@github.com> 於 2016年5月6日 星期五寫道：

**Comment by c9s** [comment] 2016-05-06 16:15
Not sure why you have this timeout, I can't reproduce this.

**Comment by c9s** [comment] 2016-05-06 16:16
```
phpbrew ext install xdebug                                                                                    !12180
Warning: Some extension won't be able to be built with php7. If the extension
supports php7 in another branch or new major version, you will need to specify
the branch name or version name explicitly.

For example, to install memcached extension for php7, use:

    phpbrew ext install github:php-memcached-dev/php-memcached php7 -- --disable-memcached-sasl

Downloading http://pecl.php.net/get/xdebug-2.4.0.tgz via curl extension
[==================================================================] 258.62/258.62KB 100%
===> Extracting to /Users/c9s/.phpbrew/build/7.0/ext...
===> Installing xdebug extension...
Log stored at: /Users/c9s/.phpbrew/build/7.0/ext/xdebug/build.log
Changing directory to /Users/c9s/.phpbrew/build/7.0/ext/xdebug
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: /opt/local/bin/gmake -C '/Users/c9s/.phpbrew/build/7.0/ext/xdebug' 'all'  >> '/Users/c9s/.phpbrew/build/7.0/ext/xdebug/build.log' 2>&1
===> Installing...
===> Running make install: /opt/local/bin/gmake -C '/Users/c9s/.phpbrew/build/7.0/ext/xdebug' 'install'  >> '/Users/c9s/.phpbrew/build/7.0/ext/xdebug/build.log' 2>&1
===> Extension is installed.
===> Creating config file /Users/c9s/.phpbrew/php/7.0/var/db/xdebug.ini.disabled
===> Enabling extension xdebug
[*] xdebug extension is enabled.
Done.
```

**Comment by jhdxr** [comment] 2016-05-06 17:08
Resolving timed out usually happens when you have a network problem, especially the DNS problem. 
try `ping pecl.php.net` to see if your network is ok.

**Comment by Serginho** [comment] 2016-05-06 17:30
My internet connection is quite fast. I've tried several days and always have the same problem.

I'm alsolutely sure that's a curl problem. For example, the exception says this:
0) CurlKit\CurlDownloader->request('https://pecl.php.net/rest/r/xdebug/stable.txt')
If I copy the url and use the browser, there's no problem.

**Comment by Serginho** [comment] 2016-05-06 17:36
By the way. I've tried at work and at home. Diferent connection and the same problem.

If I executed phpbrew install php-7.0.6 and the exception is thrown. I copied the link, downloaded the file from the browser and put it into distfiles folder. After that I executed the command again and it works cause the php version had already downloaded

**Comment by c9s** [comment] 2016-05-07 14:21
Ok maybe some server disallowed curl request, could you try that link with curl command?

**Comment by c9s** [comment] 2016-05-07 14:22
Btw I updated the curlkit with user agent string, it might happen when user agent string is not set.

**Comment by jhdxr** [comment] 2016-05-07 15:29
well, if you believe there is something wrong with the curl, you can use other downloader such as wget.
see https://github.com/phpbrew/phpbrew#installing-extension-with-specific-downloader for more details

**Comment by Serginho** [comment] 2016-05-08 20:52
If I execute this: phpbrew install php-7.0.6 --downloader wget
I get the same error: CurlKit Exception.... That's an weird behavior...

I've tried in another home connection and everything works properly... I have to check at work again in order to looking for dns issues... Although, I'm absolutely sure that if I execute in a shell >wget [some url] works properly... so... I have no idea what the heck is going on.

**Comment by c9s** [comment] 2016-05-09 05:45
Does `curl https://pecl.php.net/rest/r/xdebug/stable.txt` work for you?

**Comment by c9s** [comment] 2016-05-09 05:46
The command should be `phpbrew install  --downloader wget php-7.0.6`. since variant names are after the argument (version name).

**Comment by Serginho** [comment] 2016-05-09 08:47
If I execute `phpbrew install --downloader wget php-7.0.6` works properly with wget, but not with extensions, in the following code when I execute the command with wget, phpbrew returns a curl exception. How is it posible?

```
phpbrew ext install --downloader wget xdebug       
Warning: Some extension won't be able to be built with php7. If the extension
supports php7 in another branch or new major version, you will need to specify
the branch name or version name explicitly.

For example, to install memcached extension for php7, use:

    phpbrew ext install github:php-memcached-dev/php-memcached php7 -- --disable-memcached-sasl

CurlKit\CurlException: (28) Resolving timed out after 10522 milliseconds
Trace:

    0) CurlKit\CurlDownloader->request('https://pecl.php.net/rest/r/xdebug/stable.txt')
    1) PhpBrew\Extension\Provider\PeclProvider->getPackageXml('xdebug', 'stable')
    2) PhpBrew\Extension\Provider\PeclProvider->buildPackageDownloadUrl('stable')
    3) PhpBrew\Extension\ExtensionDownloader->download(PhpBrew\Extension\Provider\PeclProvider, 'stable')
    4) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('xdebug')
    5) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['xdebug'])
    6) CLIFramework\CommandBase->executeWrapper(['xdebug'])
    7) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'ext', 'install', '--downloader', 'wget', 'xdebug'])
    8) PhpBrew\Console->runWithTry(['/usr/local/bin/phpbrew', 'ext', 'install', '--downloader', 'wget', 'xdebug'])
    9) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')
```

**Comment by c9s** [comment] 2016-05-09 09:06
It's because pecl installer requires curl to query the pecl site API.

The downloader is only used for downloading the dist  file

Serginho <notifications@github.com> 於 2016年5月9日 星期一寫道：

**Comment by jhdxr** [comment] 2016-05-10 04:45
from version 1.21.6, it allows you to fetch pecl info via downloader other than curl. try `phpbrew self-update` first and then install xdebug

**Comment by Serginho** [comment] 2016-05-13 09:54
I've downloaded the last version with your fix, and here is the log:

`phpbrew ext install --downloader wget php_curl                                                                                                                255 ↵
Warning: Some extension won't be able to be built with php7. If the extension
supports php7 in another branch or new major version, you will need to specify
the branch name or version name explicitly.

For example, to install memcached extension for php7, use:

    phpbrew ext install github:php-memcached-dev/php-memcached php7 -- --disable-memcached-sasl

Found --downloader option, try to use wget as default downloader.
Downloading https://pecl.php.net/rest/r/php_curl/stable.txt via wget command
AVISO: el «timestamping» no hace nada cuando se combina con
la opción -O. Consulte el manual para más detalles.

--2016-05-13 11:52:51--  https://pecl.php.net/rest/r/php_curl/stable.txt
Resolviendo pecl.php.net (pecl.php.net)... 104.236.228.160
Conectando con pecl.php.net (pecl.php.net)[104.236.228.160]:443... conectado.
Petición HTTP enviada, esperando respuesta... 404 Not Found
2016-05-13 11:53:06 ERROR 404: Not Found.

Error: Command failed: wget --no-check-certificate -c  -N -O "/tmp/phpbrew_447ziW" "https://pecl.php.net/rest/r/php_curl/stable.txt" returns:
PHP Notice:  Undefined variable: configureOptions in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134

Notice: Undefined variable: configureOptions in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134
PHP Warning:  join(): Invalid arguments passed in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134

Warning: join(): Invalid arguments passed in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134
Configure options: `

**Comment by jhdxr** [comment] 2016-05-14 05:21
curl cannot be installed via pecl (which `phpbrew ext install` does), you have to include it when you compile php (see https://secure.php.net/manual/en/curl.installation.php)

or you can try this answer: http://serverfault.com/questions/208360/how-do-i-enable-curl-support-for-php-5-3-3
remember to use your php source path (default to `~/.phpbrew/build/php-<version>/ext/curl`) to repalce the first line.

**Comment by Serginho** [comment] 2016-05-17 09:35
Same error for phpbrew ext install pdo_pgsql

```phpbrew ext install pdo_sqlite
Warning: Some extension won't be able to be built with php7. If the extension
supports php7 in another branch or new major version, you will need to specify
the branch name or version name explicitly.

For example, to install memcached extension for php7, use:

    phpbrew ext install github:php-memcached-dev/php-memcached php7 -- --disable-memcached-sasl

===> Installing pdo_sqlite extension...
Log stored at: /home/travelflag3/.phpbrew/build/php-7.0.6/ext/pdo_sqlite/build.log
Changing directory to /home/travelflag3/.phpbrew/build/php-7.0.6/ext/pdo_sqlite
===> Phpize...
===> Configuring...
Error: Command failed: ./configure --with-php-config=/home/travelflag3/.phpbrew/php/php-7.0.6/bin/php-config >> /home/travelflag3/.phpbrew/build/php-7.0.6/ext/pdo_sqlite/build.log 2>&1 returns:
PHP Notice:  Undefined variable: configureOptions in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134

Notice: Undefined variable: configureOptions in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134
PHP Warning:  join(): Invalid arguments passed in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134

Warning: join(): Invalid arguments passed in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134
Configure options: ```

**Comment by jhdxr** [comment] 2016-05-18 04:42
@Serginho plz open a new issue, and paste your log (/home/travelflag3/.phpbrew/build/php-7.0.6/ext/pdo_sqlite/build.log).

**Closed** 2020-01-08 17:15 UTC
