### ISSUE TITLE
whereis: illegal option -- b

### ISSUE THREAD

**Issue by pierredup** [phpbrew/phpbrew#503] opened 2015-05-18 07:04 UTC
After a recent update, I'm getting the following error when trying to run `phpbrew`:

```bash
$ phpbrew
whereis: illegal option -- b
usage: whereis program [...]
```
(this comes from [bashrc#L100](https://github.com/phpbrew/phpbrew/blob/develop/shell/bashrc#L100))

The following section is from the manual page for `whereis`:

```
COMPATIBILITY
     The historic flags and arguments for the whereis utility are no longer available in this version.
```

This is on OSX Yosemite Version 10.10.3
(for reference: [Apple whereis manual ](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/whereis.1.html))

**Comment by marcioAlmada** [comment] 2015-05-19 00:52
Does it work for you if you remove `-d` option?

**Comment by pierredup** [comment] 2015-05-19 06:18
When removing that flag, I don't get any errors, but I also don't get any output.
I had to change the line to `BIN=$(which phpbrew)` to get it working again

**Comment by markwu** [comment] 2015-05-19 06:23
I have the same on OSX 10.10.3 with bash 4.3.33.

**Comment by marcioAlmada** [comment] 2015-05-19 09:00
Could you try `phpbrew self-update fix/503` and see if problem is gone?

**Comment by pierredup** [comment] 2015-05-19 09:55
:+1: That branch works for me

**Comment by marcioAlmada** [comment] 2015-05-19 12:48
Great, a minor version will be released today.

**Comment by c9s** [comment] 2015-05-19 14:52
@marcioAlmada++ great!

**Closed** 2015-05-19 17:00 UTC

**Comment by ramsey** [comment] 2015-05-27 14:14
I'm running OS X 10.10.3 with Command Line Tools 6.3 and phpbrew 1.19.1.

I'm having this same problem but with some odd behavior.

After finding this issue, I tried to run the self-update command, as suggested to get to 1.19.1, but I couldn't run `phpbrew self-update` because I kept receiving the `whereis: illegal option -- b` error message. So, I downloaded it manually, following the instructions in the README file. That's how I got to 1.19.1.

I keep my `phpbrew` in `~/bin/` rather than in `/usr/local/bin`, so that's where I put it.

After placing `phpbrew` in `~/bin/`, I am able to use it, but only when I'm in the `~` (`$HOME`) directory. If I `cd` to anywhere else on the filesystem, I see the `whereis: illegal option -- b` error.

I have tried moving `phpbrew` to `/usr/local/bin` instead, but I see the `whereis: illegal option -- b` error no matter where I try to run it, when it is located there.

**Comment by marcioAlmada** [comment] 2015-05-27 18:14
Can you try `phpbrew self-update develop`. I think the latest release on master overwritten latest fix, `whereis` is not being used anymore.

**Comment by marcioAlmada** [comment] 2015-05-27 18:24
@ramsey  just confirmed here, the release is good,. You should run `phpbrew init` **after a manual update**, so you can get the latest phpbrew shell file. When you do `self-update` this happens automatically.

**Comment by ramsey** [comment] 2015-05-27 18:48
@marcioAlmada That seems to have helped a little. Now, I no longer get the `whereis: illegal option -- b` error, but I see this:

``` console
$ phpbrew -h
phpbrew:262: command too long: phpbrew () {\n\tif [[ -e bin/phpbrew ]]\n\tthen\n\t\tBIN='bin/phpbrew' \n\telse\n\t\tBIN=$(which phpbrew) \n\tfi\n\tlocal exit_status\n\tlocal short_option\n\texport SHELL\n\tif [[ `echo $1 | awk 'BEGIN{FS=""}{print $1}'` = '-' ]]\n\tthen\n\t\tshort_option=$1 \n\t\tshift\n\telse\n\t\tshort_option="" \n\tfi\n\tcase $1 in\n\t\t(use) if [[ -z "$2" ]]\n\t\t\tthen\n\t\t\t\tif [[ -z "$PHPBREW_PHP" ]]\n\t\t\t\tthen\n\t\t\t\t\techo "Currently using system php"\n\t\t\t\telse\n\t\t\t\t\techo "Currently using $PHPBREW_PHP"\n\t\t\t\tfi\n\t\t\telse\n\t\t\t\tif [[ ! -d "$PHPBREW_ROOT/php/$2" && $2 =~ $PHPBREW_VERSION_REGEX ]]\n\t\t\t\tthen\n\t\t\t\t\t_PHP_VERSION="php-$2" \n\t\t\t\telse\n\t\t\t\t\t_PHP_VERSION=$2 \n\t\t\t\tfi\n\t\t\t\tNEW_PHPBREW_PHP_PATH="$PHPBREW_ROOT/php/$_PHP_VERSION" \n\t\t\t\tif [ -d $NEW_PHPBREW_PHP_PATH ]\n\t\t\t\tthen\n\t\t\t\t\tcode=$(command $BIN env $_PHP_VERSION) \n\t\t\t\t\tif [ -z "$code" ]\n\t\t\t\t\tthen\n\t\t\t\t\t\texit_status=1 \n\t\t\t\t\telse\n\t\t\t\t\t\teval $code\n\t\t\t\t\t\t__phpbrew_set_path\n\t\t\t\t\tfi\n\t\t\t\telse\n\t\t\t\t\techo "php version: $_PHP_VERSION not exists."\n\t\t\t\tfi\n\t\t\tfi ;;\n\t\t(cd-src) local SOURCE_DIR=$PHPBREW_HOME/build/$PHPBREW_PHP\n\t\t\tif [[ -d $SOURCE_DIR ]]\n\t\t\tthen\n\t\t\t\tcd $SOURCE_DIR\n\t\t\tfi ;;\n\t\t(switch) if [[ -z "$2" ]]\n\t\t\tthen\n\t\t\t\techo "Please specify the php version."\n\t\t\telse\n\t\t\t\t__phpbrew_reinit $2\n\t\t\tfi ;;\n\t\t(lookup-prefix) if [[ -z "$2" ]]\n\t\t\tthen\n\t\t\t\tif [[ -n $PHPBREW_LOOKUP_PREFIX ]]\n\t\t\t\tthen\n\t\t\t\t\techo $PHPBREW_LOOKUP_PREFIX\n\t\t\t\tfi\n\t\t\telse\n\t\t\t\texport PHPBREW_LOOKUP_PREFIX=$(__phpbrew_set_lookup_prefix $2)\n\t\t\t\techo $PHPBREW_LOOKUP_PREFIX\n\t\t\t\t__phpbrew_update_config\n\t\t\tfi ;;\n\t\t(install-pyrus) echo "Installing pyrus..."\n\t\t\tcd $PHPBREW_BIN && wget --no-check-certificate -c http://pear2.php.net/pyrus.phar -O pyrus && chmod +x pyrus && cd -\n\t\t\thash -r ;;\n\t\t(install-phpunit) echo "Installing phpunit..."\n\t\t\tcd $PHPBREW_BIN && wget --no-check-certificate -c https://phar.phpunit.de/phpunit.phar -O phpunit && chmod +x phpunit && cd -\n\t\t\thash -r ;;\n\t\t(install-composer) echo "Installing composer..."\n\t\t\tcd $PHPBREW_BIN && wget --no-check-certificate -c http://getcomposer.org/composer.phar -O composer && chmod +x composer && cd -\n\t\t\thash -r ;;\n\t\t(install-onion) echo "Installing onion..."\n\t\t\tcd $PHPBREW_BIN\n\t\t\twget --no-check-certificate -c https://raw.github.com/c9s/Onion/master/onion -O onion\n\t\t\tchmod +x onion\n\t\t\tcd -\n\t\t\thash -r ;;\n\t\t(cd) case $2 in\n\t\t\t\t(var) local chdir=$PHPBREW_ROOT/php/$PHPBREW_PHP/var ;;\n\t\t\t\t(etc) local chdir=$PHPBREW_ROOT/php/$PHPBREW_PHP/etc ;;\n\t\t\t\t(dist) local chdir=$PHPBREW_ROOT/php/$PHPBREW_PHP ;;\n\t\t\t\t(build) local chdir=$PHPBREW_ROOT/build/$PHPBREW_PHP ;;\n\t\t\t\t(*) echo "$2 not found"\n\t\t\t\t\treturn 0 ;;\n\t\t\tesac\n\t\t\techo "Switching to $chdir, run 'cd -' to go back."\n\t\t\tcd $chdir\n\t\t\treturn 0 ;;\n\t\t(fpm) if ! [[ -z $3 ]]\n\t\t\tthen\n\t\t\t\t_PHP_VERSION=$3 \n\t\t\telse\n\t\t\t\t_PHP_VERSION=${PHPBREW_PHP} \n\t\t\tfi\n\t\t\tmkdir -p ${PHPBREW_ROOT}/php/${_PHP_VERSION}/var/run\n\t\t\tPHPFPM_BIN=${PHPBREW_ROOT}/php/${_PHP_VERSION}/sbin/php-fpm \n\t\t\tPHPFPM_PIDFILE=${PHPBREW_ROOT}/php/${_PHP_VERSION}/var/run/php-fpm.pid \n\t\t\tfpm_start () {\n\t\t\t\techo "Starting php-fpm..."\n\t\t\t\tlocal regex="^php-5\.2.*"\n\t\t\t\tif [[ ${_PHP_VERSION} =~ ${regex} ]]\n\t\t\t\tthen\n\t\t\t\t\t${PHPFPM_BIN} start\n\t\t\t\telse\n\t\t\t\t\t${PHPFPM_BIN} --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf --pid ${PHPFPM_PIDFILE} ${*:3}\n\t\t\t\tfi\n\t\t\t\tif [[ $? != "0" ]]\n\t\t\t\tthen\n\t\t\t\t\techo "php-fpm start failed."\n\t\t\t\tfi\n\t\t\t}\n\t\t\tfpm_stop () {\n\t\t\t\tlocal regex="^php-5\.2.*"\n\t\t\t\tif [[ ${PHPBREW_PHP} =~ ${regex} ]]\n\t\t\t\tthen\n\t\t\t\t\t${PHPFPM_BIN} stop\n\t\t\t\telif [[ -e ${PHPFPM_PIDFILE} ]]\n\t\t\t\tthen\n\t\t\t\t\techo "Stopping php-fpm..."\n\t\t\t\t\tkill $(cat ${PHPFPM_PIDFILE})\n\t\t\t\t\trm -f ${PHPFPM_PIDFILE}\n\t\t\t\tfi\n\t\t\t}\n\t\t\tcase $2 in\n\t\t\t\t(start) fpm_start ;;\n\t\t\t\t(stop) fpm_stop ;;\n\t\t\t\t(restart) fpm_stop\n\t\t\t\t\tfpm_start ;;\n\t\t\t\t(module) $PHPFPM_BIN --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf -m | less ;;\n\t\t\t\t(info) $PHPFPM_BIN --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf -i ;;\n\t\t\t\t(config) if [[ -n $EDITOR ]]\n\t\t\t\t\tthen\n\t\t\t\t\t\t$EDITOR ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf\n\t\t\t\t\telse\n\t\t\t\t\t\techo "Please set EDITOR environment variable for your favor."\n\t\t\t\t\t\tnano ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf\n\t\t\t\t\tfi ;;\n\t\t\t\t(help) $PHPFPM_BIN --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf --help ;;\n\t\t\t\t(test) $PHPFPM_BIN --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf --test ;;\n\t\t\t\t(*) echo "Usage: phpbrew fpm [start|stop|restart|module|test|help|config]" ;;\n\t\t\tesac ;;\n\t\t(env) if [[ -n "$2" ]]\n\t\t\tthen\n\t\t\t\texport PHPBREW_PHP=$2\n\t\t\tfi\n\t\t\techo "export PHPBREW_ROOT=$PHPBREW_ROOT"\n\t\t\techo "export PHPBREW_HOME=$PHPBREW_HOME"\n\t\t\tif [[ -n $PHPBREW_LOOKUP_PREFIX ]]\n\t\t\tthen\n\t\t\t\techo "export PHPBREW_LOOKUP_PREFIX=$PHPBREW_LOOKUP_PREFIX"\n\t\t\tfi\n\t\t\tif [[ -n $PHPBREW_PHP ]]\n\t\t\tthen\n\t\t\t\techo "export PHPBREW_PHP=$PHPBREW_PHP"\n\t\t\t\techo "export PHPBREW_PATH=$PHPBREW_ROOT/php/$PHPBREW_PHP/bin"\n\t\t\tfi ;;\n\t\t(off) unset PHPBREW_PHP\n\t\t\tunset PHPBREW_PATH\n\t\t\teval `$BIN env`\n\t\t\t__phpbrew_set_path\n\t\t\techo "phpbrew is turned off." ;;\n\t\t(switch-off) unset PHPBREW_PHP\n\t\t\tunset PHPBREW_PATH\n\t\t\teval `$BIN env`\n\t\t\t__phpbrew_set_path\n\t\t\t__phpbrew_reinit\n\t\t\techo "phpbrew is switched off." ;;\n\t\t(rehash) echo "Rehashing..."\n\t\t\t. ~/.phpbrew/bashrc ;;\n\t\t(purge) if [[ -z "$2" ]]\n\t\t\tthen\n\t\t\t\tcommand $BIN help\n\t\t\telse\n\t\t\t\t__phpbrew_remove_purge $2 purge\n\t\t\tfi ;;\n\t\t(*) command $PHPBREW_OVERRIDE_PHP $BIN $short_option "$@"\n\t\t\texit_status=$?  ;;\n\tesac\n\thash -r\n\treturn ${exit_status:-0}\n}
```

**Comment by marcioAlmada** [comment] 2015-05-27 18:51
Holy, OSx could be more unix friendly ^^

What do you get from `echo $(command -p which phpbrew 2> /dev/null || command which phpbrew)`?

**Comment by ramsey** [comment] 2015-05-27 18:52
``` console
$ echo $(command -p which phpbrew 2> /dev/null || command which phpbrew)
/Users/ramsey/bin/phpbrew
```

**Comment by marcioAlmada** [comment] 2015-05-27 18:55
ok, and what do you get with:
`echo $(command -p which phpbrew 2> /dev/null)`
`echo $(command which phpbrew)`
?

**Comment by ramsey** [comment] 2015-05-27 19:05
Both give me the same: `/Users/ramsey/bin/phpbrew`

**Comment by marcioAlmada** [comment] 2015-05-27 19:08
ok, I'll try to find a more universal solution that works for OSx too.

**Comment by ramsey** [comment] 2015-05-27 19:10
Thanks!

**Comment by marcioAlmada** [comment] 2015-05-27 19:18
strange, this works for me on OSx too... after updating phpbrew did you reload your shell?

**Comment by davidmerrique** [comment] 2015-05-27 19:33
@marcioAlmada This same thing is happening to me too.

After removing `/usr/bin/phpbrew` and `~/.phpbrew/` then reinstalling, I get that error.

```
phpbrew:262: command too long: phpbrew () {........
```

**Comment by davidmerrique** [comment] 2015-05-27 19:38
If I remove `source ~/.phpbrew/bashrc` in my .zshrc, then the `phpbrew` command works.

Also, I noticed that when I run `phpbrew`, the version is wrong, it says `phpbrew 1.19.1`

**Comment by marcioAlmada** [comment] 2015-05-27 19:51
@davidmerrique thanks for the info, just for sake of sanity: `whereis phpbrew` ?

**Comment by davidmerrique** [comment] 2015-05-27 19:54
@marcioAlmada `/usr/bin/phpbrew`

I'm using zsh by the way

**Comment by ramsey** [comment] 2015-05-27 19:56
Oh, I'm using zsh, too. If I remove `source ~/.phpbrew/bashrc` from my `.zshrc` file, then the `phpbrew` command works fine, but I don't get get the shell prompt, and `php --version` is showing the system PHP.

**Comment by davidmerrique** [comment] 2015-05-27 20:33
@marcioAlmada Do you think the problem is zsh and not OSX? 

What if you did a check to see if zsh is running?

```bash
if [ -n "$ZSH_VERSION" ]; then
    BIN=$(whereis phpbrew)
else
    BIN=$(which phpbrew)
fi
```

**Comment by marcioAlmada** [comment] 2015-05-27 20:44
The problem is with zsh `which`, it's not the same as bash `which` + some OSx quirks related to `whereis -b` :) Let me check that. Again: what's your output for `whereis phpbrew`?

Also guys, always source source `~/.phpbrew/bashrc`, the shell wrapper is necessary.

**Comment by davidmerrique** [comment] 2015-05-27 20:52
@marcioAlmada 

```bash
$ whereis phpbrew
/usr/bin/phpbrew
```

![screen shot 2015-05-27 at 4 52 20 pm](https://cloud.githubusercontent.com/assets/867522/7847330/c282024c-0490-11e5-9e01-f30b461138f8.png)

**Comment by marcioAlmada** [comment] 2015-05-27 21:14
Indeed, I'm surprised @ramsey says he has a problem with `$(command -p which phpbrew 2> /dev/null || command which phpbrew)`. This was supposed to be universal enough.

**Comment by davidmerrique** [comment] 2015-05-27 21:28
@marcioAlmada reading back on the comments, it seems like `$(command -p which phpbrew 2> /dev/null || command which phpbrew)` was working fine for @ramsey too, no? 

He just had it installed in his home directory (`/Users/ramsey/bin/phpbrew`) instead of (`/usr/bin/phpbrew`)

When do you think we can get this in the master branch?

**Comment by greensn0w** [comment] 2015-05-27 21:41
The issue with `whereis` may be this:
> The path searched is the string returned by the sysctl(8) utility for the "user.cs_path'' string

`user.cs_path` defaults to this:
> /usr/bin:/bin:/usr/sbin:/sbin

Via: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/whereis.1.html

BTW:
Just tested `$(command -p which test 2> /dev/null || command which test)`
It even works on the minimal MINGW32 that ships with GitHub for Windows

**Comment by marcioAlmada** [comment] 2015-05-27 21:42
Great. I tested this with many OSs and it's fine here too. I'll move this to master.
