### ISSUE TITLE
Systemd not starting on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by chupnik** [phpbrew/phpbrew#780] opened 2016-07-31 18:11 UTC
### Platform

OS:
Ubuntu 16.04.1 LTS server
### Command

```
phpbrew install 5.3 +default +mysql +pdo +icu +intl +fpm +opcache +imap +exif +gd +gettext +iconv +session -- --with-mysql-sock=/var/run/mysqld/mysqld.sock --with-fpm-systemd
```
### After installing and building i've install php as service

```
phpbrew fpm setup --systemctl
```

I'm launched service and waiting for a long time command return
`systemctl start phpbrew-fpm.service`
Result of execution `systemctl status phpbrew-fpm.service`

```
root@mysrv1:~# systemctl status phpbrew-fpm.service 
● phpbrew-fpm.service - The PHPBrew FastCGI Process Manager
   Loaded: loaded (/lib/systemd/system/phpbrew-fpm.service; enabled; vendor preset: enabled)
   Active: failed (Result: timeout) since Вс 2016-07-31 21:04:20 MSK; 1min 29s ago
  Process: 2447 ExecStart=/opt/phpbrew/php/php-5.3.29/sbin/php-fpm --nodaemonize --fpm-config /opt/phpbrew/php/php-5.3.29/etc/php-
 Main PID: 2447 (code=exited, status=0/SUCCESS)

jul 31 21:02:50 mysrv1 systemd[1]: Starting The PHPBrew FastCGI Process Manager...
jul 31 21:02:50 mysrv1 php-fpm[2447]: [31-Jul-2016 21:02:50] NOTICE: fpm is running, pid 2447
jul 31 21:02:50 mysrv1 php-fpm[2447]: [31-Jul-2016 21:02:50] NOTICE: ready to handle connections
jul 31 21:04:20 mysrv1 systemd[1]: phpbrew-fpm.service: Start operation timed out. Terminating.
jul 31 21:04:20 mysrv1 php-fpm[2447]: [31-Jul-2016 21:04:20] NOTICE: Terminating ...
jul 31 21:04:20 mysrv1 php-fpm[2447]: [31-Jul-2016 21:04:20] NOTICE: exiting, bye-bye!
jul 31 21:04:20 mysrv1 systemd[1]: Failed to start The PHPBrew FastCGI Process Manager.
jul 31 21:04:20 mysrv1 systemd[1]: phpbrew-fpm.service: Unit entered failed state.
jul 31 21:04:20 mysrv1 systemd[1]: phpbrew-fpm.service: Failed with result 'timeout'.
```

**Workaround**
But after changing type of service in  `/lib/systemd/system/phpbrew-fpm.service`
`Type=notify` to `Type=simple`
and executing `systemctl daemon-reload`
service starting normally.

**Comment by marcbp** [comment] 2020-03-23 16:58
That's because systemd is waiting for health report notifications. PHP needs to compiled with systemd support to do so. FPM variant compiled by PHPBrew does not automatically add systemd support, you can turn it on with `phpbrew install <version> -- --with-fpm-systemd`.

**Comment by peter279k** [comment] 2022-12-02 08:20
The issue is resolved in the previous reply and closed now.

**Closed by peter279k** 2022-12-02 08:20 UTC
