### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by theofidry** [phpbrew/phpbrew#1317] opened 2023-01-18 23:11 UTC
I think the current CI is very limited and seeing the few hiccups during the 2.0.0 I think there is a few things that could be improved:

- The CI could be improved to test future PHP versions as well (currently it stops at 8.1)
- In order to more easily detect problematic dependencies, I think it would also be good to test against non-locked dependencies. For example, you can easily identify that doing a `composer update` will break things to not
- The CI only runs the tests, it doesn't try to build the PHAR
- Building & deploying the PHAR could be automated

If you agree with this I'm happy to help out.

**Comment by peter279k** [comment] 2023-02-04 04:05
I think the issue is very related to the #1303.

**Comment by peter279k** [comment] 2023-11-28 08:49
Fixed via the following PRs:

#1322 and #1321.

**Closed by peter279k** 2023-11-28 08:49 UTC
Labels: CI
