### ISSUE TITLE
Build PHP with phpbrew under OSX 10.11.4 & homebrew

### ISSUE THREAD

**Issue by markwu** [phpbrew/phpbrew#743] opened 2016-05-28 13:32 UTC
I try to use phpbrew 1.21.6 to build PHP-7.0.7 under OSX 10.11.4 & homebrew & PHP-7.0.6. I want to see if newest phpbrew can help me to figure out those libraries dependency.

In my original building process (since very old phpbrew version), I have to link following libraries in homebrew

```
$ brew unlink icu4c && brew link icu4c --force
$ brew unlink openssl && brew link openssl --force
$ brew unlink libxml2 && brew link libxml2 --force
```

Then, I can use phpbrew to build php with following command:

```
$ phpbrew install 5.6.21 +default +mysql +gettext=/usr/local/opt/gettext +iconv +ftp +exif +dba +openssl +soap +apxs2=/usr/local/bin/apxs
```

In phpbrew 1.21.6, I just unlink all libraries in homebrew, and using trial and error method to see if phpbrew can find all libraries dependency:

I just found phpbrew can find most dependency, but not include `openssl`,`libxml2`,`readline`, therefore I have to assign library dir for them  with the following command

```
phpbrew install 7.0.7 +default +mysql +gettext +iconv +ftp +exif +dba +openssl=/usr/local/opt/openssl +soap +apxs2 -- --with-libxml-dir=/usr/local/opt/libxml2 --with-readline=/usr/local/opt/readline
```

or replace `readline` with `libedit`

```
phpbrew install 7.0.7 +default +mysql +gettext +iconv +ftp +exif +dba +openssl=/usr/local/opt/openssl +soap +apxs2 -- --with-libedit --with-libxml-dir=/usr/local/opt/libxml2
```

I am not sure it is the expected result or not, just want to share my experience

**Comment by c9s** [comment] 2016-05-28 17:04
Thanks for your detailed report, that's helpful :)

I remember that gettext variant should automatically lookup your homebrew dependency.
https://github.com/phpbrew/phpbrew/blob/master/src/PhpBrew/VariantBuilder.php#L711

openssl lookup for homebrew
https://github.com/phpbrew/phpbrew/blob/master/src/PhpBrew/VariantBuilder.php#L498

libedit is missing the lookup.
https://github.com/phpbrew/phpbrew/blob/master/src/PhpBrew/VariantBuilder.php#L341

maybe something was wrong and the prefix lookup didn't work.

**Comment by c9s** [comment] 2016-05-29 06:23
For `--with-libedit` you can use `+editline` variant.

**Comment by c9s** [comment] 2016-05-29 06:24
BTW, you can run:

```
phpbrew --debug install 7.0.7 ....
```

to see the actual configure command before building it.

**Comment by markwu** [comment] 2016-05-29 06:57
I am outside, I will give it a try when I at home.

**Comment by markwu** [comment] 2016-05-29 13:51
I tested the following command first (without any including dirs):

```
php bin/phpbrew --debug install 7.0.6 +default +mysql +gettext +iconv +ftp +exif +dba +openssl +soap +apxs2
```

It failed when looking readline library. You can see the [debug message](https://gist.github.com/markwu/4aeb448b96418c67d312044790c16d20) and  [build log](https://gist.github.com/markwu/fc14fd6091b1271d9ef20bdcf9753764).

**Comment by markwu** [comment] 2016-05-29 14:12
It seems phpbrew does not recognize readline, but I remember it works before.

**Comment by c9s** [comment] 2016-05-29 17:08
I think it uses system's readline instead of brew's readline.

**Comment by c9s** [comment] 2016-06-12 13:45
Hi @markwu, could you try this again with 1.22.0 release? Thanks

**Comment by markwu** [comment] 2016-06-13 12:30
Ok, I'll test tonight!

**Comment by markwu** [comment] 2016-06-14 00:33
I tried  the following commands these morning, both are working as expected.

`phpbrew --debug install 7.0.6 +default +mysql +gettext +iconv +ftp +exif +dba +openssl +soap +apxs2 +editline`

`phpbrew --debug install 7.0.5 +default +mysql +gettext +iconv +ftp +exif +dba +openssl +soap +apxs2 +editline`

PHPBrew can find libxml, openssl, readline without further configurations.

Thanks for your hard works.

Mark

**Comment by markwu** [comment] 2016-06-15 04:19
I just found another weird bug. I try to install php 7.0.6 without any variants. By default it will install following modules:

```
Enabled variants: [bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, pcntl, pcre, pdo, phar, posix, readline, sockets, tokenizer, xml, curl, zip, openssl, opcache]
Disabled variants: []
```

And, the configure looks lik the following:

```
./configure '--cache-file='\''/Users/mark/.phpbrew/cache/config.cache'\''' '--prefix=/Users/mark/.phpbrew/php/php-7.0.6' '--with-config-file-path=/Users/mark/.phpbrew/php/php-7.0.6/etc' '--with-config-file-scan-dir=/Users/mark/.phpbrew/php/php-7.0.6/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash=/usr/local' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/usr/local' '--enable-pdo' '--enable-phar' '--enable-posix' '--with-readline=/usr/local/opt/readline' '--enable-sockets' '--enable-tokenizer' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr/local/opt/libxml2' '--with-curl=/usr' '--enable-zip' '--with-openssl=yes' '--enable-opcache' '--with-pear=/Users/mark/.phpbrew/php/php-7.0.6/lib/php' >> /Users/mark/.phpbrew/build/php-7.0.6/build.log 2>&1
```

You can see it didn't set `--with-openssl=/usr/local/opt/openssl`. So, it failed and come out these error messages:

```
The last 5 lines in the log file:
/Users/mark/.phpbrew/build/php-7.0.6/ext/openssl/openssl.c:44:10: fatal error: 'openssl/evp.h' file not found

#include <openssl/evp.h>

         ^

1 error generated.

make: *** [ext/openssl/openssl.lo] Error 1
```

If I change command to 

`phpbrew --debug install 7.0.6 -- --with-openssl=/usr/local/opt/openssl`  or 
`phpbrew --debug install 7.0.6 +default +openssl`, 

it works again.

**Comment by markwu** [comment] 2016-06-15 15:53
BTW, If I want to add +gd into the building process, I need to add `--with-gd=shared` in the end, or the build process will failed.

It just looks like

`phpbrew --debug install 7.0.6 +default +gd -- --with-gd=shared`

If I don't add `--with-gd=shared`, phpbrew will add it as `--with-gd=shared,/usr/local`. it will cause build failed: `fatal error: 'X11/xpm.h' file not found`.

**Comment by c9s** [comment] 2016-06-15 15:56
ok, for the gd variant, I think it's because libpng, libjpeg libraries use different prefix instead of just /usr/local, I guess this is only for homebrew...........

**Comment by c9s** [comment] 2016-06-15 15:58
yeah I saw that openssl is set to "yes", I think that's enabled for some reasons...

@marcioAlmada  do you remember the reason of enabling openssl by default?

**Comment by c9s** [comment] 2016-06-16 13:30
@markwu I reminded that we need https support when using curl or something, so openssl is required as default.

**Comment by markwu** [comment] 2016-06-17 01:10
Okay, so maybe you need to add the osx patch to default variant, or mac user have to add ` --with-openssl=/usr/local/opt/openssl` to avoid compile error.

**Comment by frankli0324** [comment] 2018-12-23 16:50
`brew info openssl` gives me
 
> For compilers to find openssl you may need to set:
>   export LDFLAGS="-L/usr/local/opt/openssl/lib"
>   export CPPFLAGS="-I/usr/local/opt/openssl/include"

and for libxml2

> For compilers to find libxml2 you may need to set:
>   export LDFLAGS="-L/usr/local/opt/libxml2/lib"
>   export CPPFLAGS="-I/usr/local/opt/libxml2/include"

same for readline

**Comment by njt1982** [comment] 2019-09-10 11:52
`+openssl="$(brew --prefix openssl)"` < This for the OpenSSL one (on OSX / Homebrew)

**Comment by peter279k** [comment] 2022-12-02 08:32
The issue is outdated and resolved in the previous reply. Closed.

**Closed by peter279k** 2022-12-02 08:32 UTC
Labels: Improvement, macOS
