### ISSUE TITLE
If PHP outputs warnings, they end up being written on ~/.phpbrew/init on switch

### ISSUE THREAD

**Issue by smola** [phpbrew/phpbrew#1192] opened 2020-08-21 08:59 UTC
### Summary

1. Using a PHP build with some kind of build problem, such as an extension built both statically and as a shared library.
2. Then `phpbrew switch ...`
3. `~/.phpbrew/init` breaks:

```
➜ cat ~/.phpbrew/init
# DO NOT EDIT THIS FILE

Warning: PHP Startup: Invalid library (maybe not a PHP library) 'bz2.so' in Unknown on line 0
export PHPBREW_ROOT=/home/user/.phpbrew
export PHPBREW_HOME=/home/user/.phpbrew
export PHPBREW_PHP=php-7.4.9
export PHPBREW_PATH=/home/user/.phpbrew/php/php-7.4.9/bin
# Run this command to configure your shell:
# eval "$(phpbrew env)"
```

So further usage breaks because there are shell errors when sourcing `~/.phpbrew/init`.

### Platform

OS: Ubuntu 20.04

Running PHP: As far as I can tell, it happens with any PHP version. The instance that produced the error for this issue is PHP 7.2.31.

**Comment by peter279k** [comment] 2022-12-01 10:37
The problem is about the `extension` loading. Some extension libraries are not loaded correctly and it will cause the init file contents are not correct.

Here are my steps to reproduce the issue:

```
$ phpbrew path ext
/home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731

$ mv /home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so /home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so.back

$ phpbrew switch 7.3.33
PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' (tried: /home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so (/home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so: cannot open shared object file: No such file or directory), /home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so.so (/home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
-bash: /home/peter/.phpbrew/init: line 3: syntax error near unexpected token `('
-bash: /home/peter/.phpbrew/init: line 3: `Warning: PHP Startup: Unable to load dynamic library 'gd.so' (tried: /home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so (/home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so: cannot open shared object file: No such file or directory), /home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so.so (/home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0'

$ cat /home/peter/.phpbrew/init

# DO NOT EDIT THIS FILE

Warning: PHP Startup: Unable to load dynamic library 'gd.so' (tried: /home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so (/home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so: cannot open shared object file: No such file or directory), /home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so.so (/home/peter/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731/gd.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
export PHPBREW_ROOT=/home/peter/.phpbrew
export PHPBREW_HOME=/home/peter/.phpbrew
export PHPBREW_LOOKUP_PREFIX=/usr/local
export PHPBREW_PHP=php-7.3.33
export PHPBREW_PATH=/home/peter/.phpbrew/php/php-7.3.33/bin
export PHPBREW_SYSTEM_PHP=/home/peter/.phpbrew/php/php-7.3.33/bin/php
# Run this command to configure your shell:
# eval "$(phpbrew env)"
```

As we can see above commands, I move the shared `gd.so` library to the `gd.so.back`.

And it will cause the `PHP Warning:  PHP Startup: Unable to load dynamic library 'gd.so' ` message when running the `phpbrew switch 7.3.33` command.

The issue is resolved by developers and it's not related to the PHPBrew.

**Closed by peter279k** 2022-12-01 10:37 UTC
Labels: Debian | Ubuntu
