### ISSUE TITLE
Unable to install apxs module with PHP 7

### ISSUE THREAD

**Issue by pierredup** [phpbrew/phpbrew#565] opened 2015-08-23 06:10 UTC
The command `phpbrew install next as PHP-7.0.0` fails with the following info:

```
Installing PHP SAPI module:       apache2handler
/usr/share/httpd/build/instdso.sh SH_LIBTOOL='/usr/share/apr-1/build-1/libtool' libs/libphp7.so /usr/libexec/apache2
/usr/share/apr-1/build-1/libtool --mode=install install libs/libphp7.so /usr/libexec/apache2/
libtool: install: install libs/libphp7.so /usr/libexec/apache2/libphp7.so
install: libs/libphp7.so: No such file or directory
apxs:Error: Command failed with rc=4653056
```

(Specifically the line `install: libs/libphp7.so: No such file or directory`)

When looking in the build directory, the module name is actually 'libphp7.0.0-dev.so' and not `libphp7.so`

I think the cause might be the following rule in the `PatchCollection:: createPatchesForApxs2 ` function, but I'm not 100% sure:
```
RegexpPatchRule::always(
    '#libs/libphp\$PHP_MAJOR_VERSION\.#',
    'libs/libphp$PHP_VERSION.'
),
```

**Comment by markwu** [comment] 2015-11-08 15:08
I just got the same error when compiling php-7.0.0 from master branch.

**Comment by c9s** [comment] 2015-11-08 16:29
Yes it's caused by the apxs2 patch (out of date for php7)

**Comment by c9s** [comment] 2015-11-08 16:31
The solution was mentioned #339 but I don't have time to fix it yet...

**Comment by c9s** [comment] 2015-12-07 13:38
Fixed in 1.20.2 release, however I noticed that php7 with apache2 will cause apache crash (core dump)

**Closed by c9s** 2015-12-07 13:38 UTC

**Comment by vincenzo-mennella** [comment] 2016-01-13 15:21
>however I noticed that php7 with apache2 will cause apache crash (core dump)

Do you have any news about this error?

**Comment by pierredup** [comment] 2016-01-13 16:13
I'm currently running PHP 7 on apache without any issues, so I'm not sure if it's still an issue

**Comment by vincenzo-mennella** [comment] 2016-01-13 16:15
@pierredup could you please provide some more details about your configuration? What file(s) did you edit? Thanks.

**Comment by pierredup** [comment] 2016-01-13 19:35
I didn't need to edit any files. I just did a normal install of PHP 7 with the APXS module, and enabled the `php7_module` in my apache config (disabling the `php5_module` as well, off course)

**Comment by vincenzo-mennella** [comment] 2016-01-15 16:00
@pierredup thank you for your reply.

I'm still in trouble with this... Still not getting results (except for some segmentation faults...)

Could you please explain a little better what files did you change and what did you write in? (maybe with some example configuration). I'm trying to use PHP 5.5.9 and 7.0.2, but only the switch in CLI works fine.

Thanks a lot.

@c9s do you have some docs about the Apache configuration?

**Comment by pierredup** [comment] 2016-01-17 14:43
I added the following to my httpd.conf file:

```
LoadModule php7_module        libexec/apache2/libphp7.0.1.so

<IfModule php7_module>
        AddType application/x-httpd-php .php
        AddType application/x-httpd-php-source .phps

        <IfModule dir_module>
                DirectoryIndex index.html index.php
        </IfModule>
</IfModule>
```

and removed everything that has `php5_module`

**Comment by vincenzo-mennella** [comment] 2016-01-19 10:20
@pierredup 
Great! Under Apache 2.4.7 I had to rename /etc/apache2/mods-enabled/php5.load in something different (php5.load.back is OK) and restart apache in order to get the work done :)

Now seems to be OK! Thank you!
