### ISSUE TITLE
.phpbrewrc-files have no impact, concatenation of strings in bashrc never works

### ISSUE THREAD

**Issue by DavidBruchmann** [phpbrew/phpbrew#791] opened 2016-09-20 23:38 UTC
I never get .phpbrewrc-files running, no matter which of the following lines I place in the file:

phpbrew use 5.6.26
phpbrew use php-5.6.26
phpbrew switch 5.6.26
phpbrew switch php-5.6.26

I place surly only one at the same time in a file.
In terminal I can switch, see the bash-output below.

In the bash I get a strange output when calling a php-file where I placed a .phpbrewrc-file in the directory:
### Output

  not exists. 5.6.26
### Expected Result

php-version: 5,6,26 not exists.`
### Details

as the bash is already messing the things up, I assume the whole logic of the script is not working.
I never used phpbrew with lower ubuntu-versions so I've no comparison.
I'm trying on the ssh-console and don't know which terminal is loaded exactly but I have only a .bashrc-file in the directory /root/ and no .zshrc-file, additionally my entries in the ,bashrc-file seems working in general, just the script not.
### COMMAND

phpbrew --debug --log-path=/root/.phpbrew/ install 5.6.26 +mysql+gd+cgi+apxs2+debug
### Bash

Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-38-generic x86_64)
 . . .
Last login: Wed Sep 21 05:11:35 2016 from 180.253.5.245
~ > root@domain [php:7.0.8 -phpbrew]

> cd /var/www/html/domain.com
> /var/www/html/domain.com > root@domain [php:7.0.8 -phpbrew]
> php -f test.php
>  not exists. php-5.6.26
> Current PHP-Version: 7.0.8 (Output of php-test-script)
> /var/www/html/domain.com > root@domain [php:7.0.8 -phpbrew]
> phpbrew use php-5.6.26
> /var/www/html/domain.com > root@domain [php:5.6.26-phpbrew]
> php -f test.php
> Current PHP-Version: 5.6.26 (Output of php-test-script)
> /var/www/html/domain.com > root@domain [php:5.6.26-phpbrew]
### Platform

OS:  Ubuntu 16.04.1

Running PHP:  7.0.8

Installing PHP: 5.6.26

**Comment by Shotman** [comment] 2018-05-16 12:34
I have the same issue is here is the console output : 

```
$ php -v
PHP 7.2.5 (cli) (built: May 16 2018 14:04:53) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

$ cd Documents/perso/test 
$ cat .phpbrewrc 
phpbrew use php-7.1.17

$ php -v
PHP 7.2.5 (cli) (built: May 16 2018 14:04:53) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

**Comment by kevinnio** [comment] 2018-10-26 06:34
Looks like this is a really old issue, but just in case someone gets here while googling, you need to set `PHPBREW_RC_ENABLE=1` in your `.bashrc` or `.zshrc` file.

```bash
export PHPBREW_RC_ENABLE=1
source ~/.phpbrew/bashrc
```

**Comment by peter279k** [comment] 2022-12-02 08:14
The issue is resolved in the previous reply. It's going to be closed.

**Closed by peter279k** 2022-12-02 08:14 UTC
Labels: .phpbrewrc
