### ISSUE TITLE
InstallCommand.php needs migration to PHP8

### ISSUE THREAD

**Issue by benjamindulau** [phpbrew/phpbrew#1298] opened 2022-12-16 15:09 UTC
### Output

```
===> Checking patches...
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
4 changes patched.
Checking patch for php5.6 with openssl 1.1.x patch.
===> Building...
Build finished: 11.7 minutes.
Installing...
---> Creating php.ini
---> Copying /Users/benjamin/.phpbrew/build/php-8.1.12/php.ini-development
Found existing /Users/benjamin/.phpbrew/php/php-8.1.12/etc/cli/php.ini.
---> Found date.timezone is not set, patching...
Initializing pear config...
config-set succeeded
config-set succeeded
config-set succeeded
Enabling pear auto-discover...
config-set succeeded
Congratulations! Now you have PHP with 8.1.12 as php-8.1.12
PHP Fatal error:  Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/InstallCommand.php:580
Stack trace:
#0 phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/InstallCommand.php(580): implode(Array, '\n')
#1 [internal function]: PhpBrew\Command\InstallCommand->execute('8.1.12', '+default', '+ftp', '+gd', '+iconv', '+intl', '+pdo', '+sodium', '+sqlite', '+zlib', '+opcache')
#2 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php(846): call_user_func_array(Array, Array)
#3 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php(398): CLIFramework\CommandBase->executeWrapper(Array)
#4 phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php(105): CLIFramework\Application->run(Array)
#5 phar:///usr/local/bin/phpbrew/bin/phpbrew(26): PhpBrew\Console->runWithTry(Array)
#6 /usr/local/bin/phpbrew(14): require('phar:///usr/loc...')
#7 {main}
  thrown in phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/InstallCommand.php on line 580

Fatal error: Uncaught TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/InstallCommand.php on line 580

TypeError: implode(): Argument #2 ($array) must be of type ?array, string given in phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/InstallCommand.php on line 580

Call Stack:
    0.0023    2075072   1. {main}() /usr/local/bin/phpbrew:0
    0.0360    2794416   2. require('phar:///usr/local/bin/phpbrew/bin/phpbrew') /usr/local/bin/phpbrew:14
    0.0438    3418488   3. PhpBrew\Console->runWithTry($argv = [0 => '/usr/local/bin/phpbrew', 1 => 'install', 2 => '8.1.12', 3 => '+default', 4 => '+ftp', 5 => '+gd', 6 => '+iconv', 7 => '+intl', 8 => '+pdo', 9 => '+sodium', 10 => '+sqlite', 11 => '+zlib', 12 => '+opcache']) phar:///usr/local/bin/phpbrew/bin/phpbrew:26
    0.0438    3418488   4. CLIFramework\Application->run($argv = [0 => '/usr/local/bin/phpbrew', 1 => 'install', 2 => '8.1.12', 3 => '+default', 4 => '+ftp', 5 => '+gd', 6 => '+iconv', 7 => '+intl', 8 => '+pdo', 9 => '+sodium', 10 => '+sqlite', 11 => '+zlib', 12 => '+opcache']) phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php:105
    0.1670    5198312   5. CLIFramework\CommandBase->executeWrapper($args = [0 => '8.1.12', 1 => '+default', 2 => '+ftp', 3 => '+gd', 4 => '+iconv', 5 => '+intl', 6 => '+pdo', 7 => '+sodium', 8 => '+sqlite', 9 => '+zlib', 10 => '+opcache']) phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php:398
    0.1670    5198896   6. call_user_func_array:{phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php:846}($callback = [0 => class PhpBrew\Command\InstallCommand { protected $commands = [...]; protected $commandGroups = [...]; protected $aliases = [...]; public $options = class GetOptionKit\OptionResult { ... }; public $parent = class PhpBrew\Console { ... }; public $optionSpecs = class GetOptionKit\OptionCollection { ... }; protected $argInfos = class CLIFramework\ArgInfoList { ... }; protected $extensions = [...]; public $application = NULL; public $name = 'install' }, 1 => 'execute'], $args = [0 => '8.1.12', 1 => '+default', 2 => '+ftp', 3 => '+gd', 4 => '+iconv', 5 => '+intl', 6 => '+pdo', 7 => '+sodium', 8 => '+sqlite', 9 => '+zlib', 10 => '+opcache']) phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php:846
    0.1671    5198968   7. PhpBrew\Command\InstallCommand->execute($version = '8.1.12', '+default', '+ftp', '+gd', '+iconv', '+intl', '+pdo', '+sodium', '+sqlite', '+zlib', '+opcache') phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php:846
  810.2419    6137512   8. implode($separator = [0 => '    /Users/benjamin/.phpbrew/php/php-8.1.12/etc/cli/php.ini'], $array = '\n') phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/InstallCommand.php:580
```

### Expected Result

```
Successful installation.
```

### Command

phpbrew install 8.1.12 +default +ftp +gd +iconv +intl +pdo +sodium +sqlite +zlib +opcache

### Platform

OS:

    e.g. OS X 13.1 (Ventura)

**Comment by peter279k** [comment] 2022-12-16 15:26
Thanks. The issue is fixed in the PR https://github.com/phpbrew/phpbrew/pull/1290.

**Closed by peter279k** 2022-12-16 15:26 UTC

**Comment by benjamindulau** [comment] 2022-12-16 15:31
How can we temporarily apply the patch on macOS while waiting for the release?

**Comment by peter279k** [comment] 2022-12-16 15:54
At this moment, we don't have the current patch on the any operating system.

To resolve the issue temporarily, you can use the `PHP 7.4` version to run the PHPBrew.

Just notice that the PHPBrew has been inactive for about one year and there're many PHP 8.x compatibility issues are resolved in the recent commits and PRs.

Please wait for whiles and I'v created the PR #1299 to release the `2.0.0` and I believe it will be merged soon :).

**Comment by benjamindulau** [comment] 2022-12-16 16:19
Ho ok I think I wasn't understanding the issue correctly, I'll try to switch to php7.4 before trying to install.
Thanks. GL with the new version :)

**Comment by peter279k** [comment] 2022-12-16 16:45
@benjamindulau, the first [2.x version](https://github.com/phpbrew/phpbrew/releases/tag/2.0.0) is released. Please use that happily :).
