### ISSUE TITLE
Unable to install 5.6 or 7.0

### ISSUE THREAD

**Issue by keithslater** [phpbrew/phpbrew#636] opened 2015-12-13 19:12 UTC
Trying to install 5.6 or 7.0 I receive this error:

```
Undefined symbols for architecture x86_64:
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _zif_openssl_pbkdf2 in openssl.o
  "_SSL_CTX_set_alpn_protos", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_SSL_CTX_set_alpn_select_cb", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_SSL_get0_alpn_selected", referenced from:
      _php_openssl_sockop_set_option in xp_ssl.o
  "_SSL_select_next_proto", referenced from:
      _server_alpn_callback in xp_ssl.o
  "_TLSv1_1_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_1_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp7.0.0.bundle] Error 1
```

I have tried -

    brew link libxml2 --force

And it doesn't fix it. Any other suggestions?

**Comment by c9s** [comment] 2015-12-14 11:40
Have you brew link openssl?

I remember there is wiki page for that.

**Comment by keithslater** [comment] 2015-12-14 14:10
Yes - 

    Warning: Already linked: /usr/local/Cellar/openssl/1.0.2e

**Comment by AnthonyPorthouse** [comment] 2015-12-15 11:16
:+1: I also have this problem, even with openssl linked.

**Comment by c9s** [comment] 2015-12-15 13:06
You will need `+openssl=/usr/local/Cellar/openssl/1.0.2e` I guess

**Comment by c9s** [comment] 2015-12-15 13:08
See #637 for the detailed usage

**Comment by AnthonyPorthouse** [comment] 2015-12-15 14:20
@c9s While that looks correct, building still fails with the same issues that were patched in #637, since that was merged into develop and have not since been merged back into master, but develop itself is behind master.

Running: `phpbrew install -j 4 7.0.0 +default +openssl=/usr/local/Cellar/openssl/1.0.2e -- --with-openssl=/usr/local/Cellar/openssl/1.0.2e`
Resolves to the following configuration options
```
Configure options: --disable-all --enable-phar --enable-session --enable-short-tags --enable-tokenizer --with-pcre-regex --with-zlib=/usr --with-openssl=/usr/local --enable-dom --enable-libxml --enable-simplexml --enable-xml --enable-xmlreader --enable-xmlwriter --with-xsl --with-libxml-dir=/usr --enable-bcmath --with-bz2=/usr --enable-calendar --enable-cli --enable-ctype --enable-dom --enable-fileinfo --enable-filter --enable-shmop --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-json --enable-mbregex --enable-mbstring --with-mhash=/usr/local --with-mcrypt=/usr/local --enable-pcntl --with-pcre-regex --with-pcre-dir=/usr/local --enable-pdo --enable-phar --enable-posix --with-readline=/usr --with-libedit=/usr --enable-sockets --enable-tokenizer --with-curl=/usr/local --enable-zip
```

Which of course still errors since it is still looking for openssl in /usr/local

**Comment by morozov** [comment] 2015-12-17 02:53
@AnthonyPorthouse it may be because of #637. Not sure if the fixed version has been released.

**Comment by c9s** [comment] 2015-12-17 04:51
Yes it's released

Sergey Morozov <notifications@github.com> 於 2015年12月17日 星期四寫道：

**Comment by keithslater** [comment] 2015-12-31 05:36
Is there any solution to this yet?

**Comment by c9s** [comment] 2016-01-14 05:02
You need to run self-update and use the options like: `+openssl=/usr/local/Cellar/openssl/1.0.2e +gettext=/usr/local/Cellar/gettext/0.19.7`

Reference: https://github.com/phpbrew/phpbrew/pull/656/files

**Comment by AnthonyPorthouse** [comment] 2016-01-14 09:45
@c9s This is still an issue for me

```
 anthony@Eowyn  ~  phpbrew self-update
Updating phpbrew /usr/local/bin/phpbrew from master...
######################################################################## 100.0%
Version updated.
Checking directory /Users/anthony/.phpbrew
Directory /Users/anthony/.phpbrew is already created.
Checking directory /Users/anthony/.phpbrew
Directory /Users/anthony/.phpbrew is already created.
Checking directory /Users/anthony/.phpbrew/register
Directory /Users/anthony/.phpbrew/register is already created.
Checking directory /Users/anthony/.phpbrew/build
Directory /Users/anthony/.phpbrew/build is already created.
Checking directory /Users/anthony/.phpbrew/php
Directory /Users/anthony/.phpbrew/php is already created.
Creating .metadata_never_index to prevent SpotLight indexing
Initialization successfully finished!
<=====================================================>
Phpbrew environment is initialized, required directories are created under

    /Users/anthony/.phpbrew

Paste the following line(s) to the end of your ~/.bashrc and start a
new shell, phpbrew should be up and fully functional from there:

    source /Users/anthony/.phpbrew/bashrc

To enable PHP version info in your shell prompt, please set PHPBREW_SET_PROMPT=1
in your `~/.bashrc` before you source `~/.phpbrew/bashrc`

    export PHPBREW_SET_PROMPT=1

For further instructions, simply run `phpbrew` to see the help message.

Enjoy phpbrew at $HOME!!

<=====================================================>
phpbrew - 1.20.5
cliframework core: 2.5.4
 anthony@Eowyn  ~  phpbrew install 7.0.2 +default +openssl=/usr/local/Cellar/openssl/1.0.2e_1
===> phpbrew will now build 7.0.2
===> Loading and resolving variants...
===> Downloading from http://www.php.net/get/php-7.0.2.tar.bz2/from/this/mirror
Redirecting to http://nl1.php.net/distributions/php-7.0.2.tar.bz2
[==================================================================] 13.34/13.34MB 100%
===> /Users/anthony/.phpbrew/distfiles/php-7.0.2.tar.bz2 downloaded.
===> Extracting /Users/anthony/.phpbrew/distfiles/php-7.0.2.tar.bz2 to /Users/anthony/.phpbrew/tmp/php-7.0.2
===> Moving /Users/anthony/.phpbrew/tmp/php-7.0.2 to /Users/anthony/.phpbrew/build/php-7.0.2
===> Configuring 7.0.2...


Use tail command to see what's going on:
   $ tail -F /Users/anthony/.phpbrew/build/php-7.0.2/build.log


===> Building...

Error: Make failed.
Configure options: --disable-all --enable-phar --enable-session --enable-short-tags --enable-tokenizer --with-pcre-regex --with-zlib=/usr --with-openssl=/usr/local/Cellar/openssl/1.0.2e_1 --enable-dom --enable-libxml --enable-simplexml --enable-xml --enable-xmlreader --enable-xmlwriter --with-xsl --with-libxml-dir=/usr --enable-bcmath --with-bz2=/usr --enable-calendar --enable-cli --enable-ctype --enable-dom --enable-fileinfo --enable-filter --enable-shmop --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-json --enable-mbregex --enable-mbstring --with-mhash=/usr/local --with-mcrypt=/usr/local --enable-pcntl --with-pcre-regex --with-pcre-dir=/usr/local --enable-pdo --enable-phar --enable-posix --with-readline=/usr --with-libedit=/usr --enable-sockets --enable-tokenizer --with-curl=/usr/local --enable-zip
Last 5 lines in the log file:
  "_TLSv1_2_server_method", referenced from:

      _php_openssl_setup_crypto in xp_ssl.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [sapi/cli/php] Error 1

Please checkout the build log file for more details:
	 tail /Users/anthony/.phpbrew/build/php-7.0.2/build.log
```

**Comment by c9s** [comment] 2016-01-14 10:27
Looks like you have the issue pointed here: https://github.com/Homebrew/homebrew-php/issues/1931 <https://github.com/Homebrew/homebrew-php/issues/1931>

**Comment by leondeng** [comment] 2016-02-02 11:42
export LDFLAGS="/usr/local/opt/openssl/lib/libssl.dylib /usr/local/opt/openssl/lib/libcrypto.dylib"

in terminal, before you do phpbrew install.

**Comment by esaveya** [comment] 2016-03-30 12:04
Thank you @leondeng, this tip fixed the issue for my situation. Much appreciated!

**Comment by Ma-Xiaolei** [comment] 2016-04-13 01:48
I had the same error when I installed ```+apxs2```  on El Capitan.
```$ sudo phpbrew install php-5.6.13 +default+mysql+pdo+mb+phar+apxs2```
I tried everything which I could find by google and all failed.
I just fixed it with '''+openssl=shared'''.
```$ sudo phpbrew install php-5.6.13 +default+mysql+pdo+mb+phar+apxs2 +openssl=shared```

**Comment by c9s** [comment] 2016-04-22 16:55
I finally found the root cause, PHP's build system's fault, The new OS X has taken out the built-in ssl, so you have to install openssl by yourself and fix the Makefile, steps are below:


1. Find two dylib files (I am using Macports, therefore I am looking for the files under /opt/local)
    find /opt/local/lib -name "libcrypto.dylib"
    find /opt/local -name "libssl.dylib"
2. Go to the source directory
3. Edit Makefile
4. Find `EXTRA_LIBS = `
5. Replace `-lssl` and `-lcrypto` with the absolute path of `libcrypto.dylib` and `libssl.dylib`
6. So it becomes: `EXTRA_LIBS = /opt/local/lib/libcrypto.dylib /opt/local/lib/libssl.dylib ....`

**Closed by c9s** 2016-04-22 16:55 UTC
Labels: Support

**Comment by c9s** [comment] 2016-04-22 17:43
I created a PHP patch for this, released in latest phpbrew. (just now)
