### ISSUE TITLE
The Location header can not be found: HTTP/2 302

### ISSUE THREAD

**Issue by Striffly** [phpbrew/phpbrew#1011] opened 2019-04-19 15:35 UTC
### Output

```bash
===> phpbrew will now build 7.3.4
===> Loading and resolving variants...
Downloading http://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror via curl extension
[==================================================================] 185.00/185.00B 100%
Redirecting to https://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror
CurlKit\CurlException:  at [The Location header can not be found: HTTP/2 302 
server: myracloud
date: Fri, 19 Apr 2019 15:32:39 GMT
content-type: text/html; charset=utf-8
content-language: en
x-frame-options: SAMEORIGIN
set-cookie: COUNTRY=NA%2C92.154.54.148; expires=Fri, 26-Apr-2019 15:32:39 GMT; Max-Age=604800; path=/; domain=.php.net
x-php-load: 0.35, 0.34, 0.3
status: 302 Found
location: https://www.php.net/distributions/php-7.3.4.tar.bz2
expires: Fri, 19 Apr 2019 15:32:39 GMT
cache-control: max-age=0]
Trace:

    0) CurlKit\CurlDownloader->request('https://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror', [], ['https://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror'])
    1) CurlKit\CurlDownloader->request('http://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror')
    2) PhpBrew\Downloader\PhpCurlDownloader->process('http://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror', '/home/clement/.phpbrew/distfiles/php-7.3.4.tar.bz2')
    3) PhpBrew\Downloader\BaseDownloader->download('http://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror', '/home/clement/.phpbrew/distfiles/php-7.3.4.tar.bz2')
    4) PhpBrew\Tasks\DownloadTask->download('http://www.php.net/get/php-7.3.4.tar.bz2/from/this/mirror', '/home/clement/.phpbrew/distfiles', 'sha256', '2e2c3d8212c83649e443b61efffbd03df4b9edd0f9c7a679081fe4cb2da12b78')
    5) PhpBrew\Command\InstallCommand->execute('7.3.4', '+bcmath', '+bz2', '+calendar', '+cli', '+curl', '+dom', '+fileinfo', '+filter', '+gd', '+ipc', '+iconv', '+json', '+mysql', '+mbregex', '+mbstring', '+openssl', '+pcntl', '+pcre', '+pdo', '+phar', '+posix', '+readline', '+sockets', '+tokenizer', '+session', '+xml', '+zip', '+zlib', '+filter', '+ctype', '+fpm', '+hash')
    6) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['7.3.4', '+bcmath', '+bz2', '+calendar', '+cli', '+curl', '+dom', '+fileinfo', '+filter', '+gd', '+ipc', '+iconv', '+json', '+mysql', '+mbregex', '+mbstring', '+openssl', '+pcntl', '+pcre', '+pdo', '+phar', '+posix', '+readline', '+sockets', '+tokenizer', '+session', '+xml', '+zip', '+zlib', '+filter', '+ctype', '+fpm', '+hash'])
    7) CLIFramework\CommandBase->executeWrapper(['7.3.4', '+bcmath', '+bz2', '+calendar', '+cli', '+curl', '+dom', '+fileinfo', '+filter', '+gd', '+ipc', '+iconv', '+json', '+mysql', '+mbregex', '+mbstring', '+openssl', '+pcntl', '+pcre', '+pdo', '+phar', '+posix', '+readline', '+sockets', '+tokenizer', '+session', '+xml', '+zip', '+zlib', '+filter', '+ctype', '+fpm', '+hash'])
    8) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'install', '7.3.4', '+bcmath', '+bz2', '+calendar', '+cli', '+curl', '+dom', '+fileinfo', '+filter', '+gd', '+ipc', '+iconv', '+json', '+mysql', '+mbregex', '+mbstring', '+openssl', '+pcntl', '+pcre', '+pdo', '+phar', '+posix', '+readline', '+sockets', '+tokenizer', '+session', '+xml', '+zip', '+zlib', '+filter', '+ctype', '+fpm', '+hash'])
    9) PhpBrew\Console->runWithTry(['/usr/local/bin/phpbrew', 'install', '7.3.4', '+bcmath', '+bz2', '+calendar', '+cli', '+curl', '+dom', '+fileinfo', '+filter', '+gd', '+ipc', '+iconv', '+json', '+mysql', '+mbregex', '+mbstring', '+openssl', '+pcntl', '+pcre', '+pdo', '+phar', '+posix', '+readline', '+sockets', '+tokenizer', '+session', '+xml', '+zip', '+zlib', '+filter', '+ctype', '+fpm', '+hash'])
    10) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')
```

### Expected Result

Compiles & Install PHP successfully

### Command

```bash
phpbrew install 7.3.4 +bcmath +bz2 +calendar +cli +curl +dom +fileinfo +filter +gd +ipc +iconv +json +mysql +mbregex +mbstring +openssl +pcntl +pcre +pdo +phar +posix +readline +sockets +tokenizer +session +xml +zip +zlib +filter +ctype +fpm +hash
```
But I have same result for any version of php I try to install

### Platform

OS: ArchLinux kernel 5.0.7-arch1-1-ARCH
Running PHP: 7.3.4
Tested on two computers with exactly same config, but different networks

**Comment by marmotz** [comment] 2019-04-21 08:35
Same here with Manjaro kernel 5.0.5-1-MANJARO and following command :
```
phpbrew install \
     -j $(nproc) \
     --name=7.3 \
     7.3  \
     +curl +iconv +intl +pdo +mysql +pgsql +sqlite +json +ctype +hash +filter +posix +mbstring +openssl +zip
```

**Comment by marmotz** [comment] 2019-04-21 08:42
@Striffly Add --mirror=https://www.php.net fixed my problem

**Comment by V13Axel** [comment] 2019-04-23 13:41
@marmotz my `phpbrew` doesn't seem to have a --mirror option. 

I'm also seeing this on Manjaro. On looking at the list of headers, there's definitely a `location` header, but it looks like `phpbrew` is expecting `Location`, case-sensitive?

**Comment by V13Axel** [comment] 2019-04-23 13:51
It looks like the case-sensitivity is an issue within CurlKit/CurlDownloader:

https://github.com/c9s/CurlKit/blob/675b4a93737c318cfffbad5c4f084a0325c4c2ed/src/CurlKit/CurlDownloader.php#L174

**Comment by marmotz** [comment] 2019-04-23 15:03
@V13Axel 
```
$ phpbrew help install
...
OPTIONS
...
	--mirror=<value>
		Use specified mirror site. phpbrew will download the files from
		[mirror]/distributions/*
```

so
```
phpbrew install \
    -j $(nproc) \
    --name=7.3 \
    --mirror=https://www.php.net \
    7.3  \
    +curl +iconv +intl +pdo +mysql +sqlite +json +ctype +hash +filter +posix +mbstring +openssl +zip
```
works for me

**Comment by adiaga** [comment] 2019-04-23 16:25
@marmotz 
Confirmed adding --mirror to install works.

@V13Axel
--mirror is an phpbrew install option not phpbrew option
So you need to have phpbrew install --mirror=https://www.php.net ....

**Comment by V13Axel** [comment] 2019-04-23 17:36
Yep, I can confirm it works as well.

**Comment by Calosha** [comment] 2019-04-26 19:12
thanks for --mirror=https://www.php.net worked for me as well

**Comment by Striffly** [comment] 2019-04-29 08:14
> @Striffly Add --mirror=https://www.php.net fixed my problem

@marmotz thanks for your solution, works for me as well !
So now we just need a fix in repo

**Comment by btassone** [comment] 2019-05-09 15:30
> > @Striffly Add --mirror=https://www.php.net fixed my problem
> 
> @marmotz thanks for your solution, works for me as well !
> So now we just need a fix in repo

To the end that you mentioned, I found this thread after coming from https://github.com/phpbrew/phpbrew/wiki/Quick-Start and experiencing the same problem for this step:

# Let's brew something out.
phpbrew --debug install --stdout 7.0 as 7.0-dev +default +intl -- # put your extra configure options here, e.g. --with-readline=...

This was the fix for me as well, thanks!

**Comment by jochen42** [comment] 2019-05-11 08:36
Hi @c9s,

the already merged [pr](https://github.com/c9s/CurlKit/pull/6) of your **CurlKit** would fixes this problem.
It would be cool to create an current release to be able to create a pr here.

have a great time! jochen

**Comment by act28** [comment] 2019-05-24 01:53
This is still an issue in `phpbrew 1.23.1`.
Also, note that the PHP mirrors program has been [retired](https://derickrethans.nl/php-mirrors.html).
`phpbrew install --mirror=https://www.php/net {version} {variants}` works for now, but isn't necessary anymore since everything is already behind a CDN.

**Comment by hadifarnoud** [comment] 2019-08-24 09:21
I still have this issue and only adding `--mirror=https://www.php.net` fixed the issue only to run into this
```
===> Configuring 7.3.8...


Use tail command to see what's going on:
   $ tail -F /Users/hadifarnoud/.phpbrew/build/php-7.3.8/build.log


Error: Configure failed:
The last 5 lines in the log file:
checking for cc... cc

checking whether the C compiler works... no

configure: error: in `/Users/hadifarnoud/.phpbrew/build/php-7.3.8':

configure: error: C compiler cannot create executables

See `config.log' for more details

Please checkout the build log file for more details:
	 tail /Users/hadifarnoud/.phpbrew/build/php-7.3.8/build.log
```

**Comment by njt1982** [comment] 2019-09-10 10:15
Yup - helped me too: `phpbrew install --mirror=https://www.php.net 7.2.22`

**Comment by HeathNaylor** [comment] 2019-10-03 20:21
@njt1982 your solution works.

**Comment by PatricNox** [comment] 2019-10-11 07:19
Nope 🚫 
> phpbrew install 7.2.22 --mirror=https://www.php.net

Yep ✅ 
> phpbrew install --mirror=https://www.php.net 7.2.22

**Comment by morozov** [comment] 2019-11-01 17:03
This must be the change that caused the regression https://github.com/c9s/CurlKit/pull/4/files#r312761591.

**Closed** 2019-11-29 23:13 UTC
Labels: Bug, Downloaders

**Comment by mahagr** [comment] 2019-12-19 08:28
Also command `phpbrew update` fails because of 301 redict; it looks like  https://secure.php.net is no more.

**Comment by caiuspupus86** [comment] 2019-12-19 09:58
@mahagr same for me, `phpbrew update` fails with `CurlKit\CurlException:  at [The Location header can not be found: HTTP/2 301`.
Any idea ?

**Comment by morozov** [comment] 2019-12-19 15:36
@caiuspupus86 which PHPBrew version are you using? It must have been solved by #1038.

**Comment by mahagr** [comment] 2019-12-20 07:45
I'm using the latest released version, updated yesterday.

**Comment by morozov** [comment] 2019-12-21 08:33
Sorry for the confusion. This fix is not yet released. See the associated milestone.

**Comment by autaut03** [comment] 2019-12-21 17:00
For now, you can clone phpbrew and run `./bin/phpbrew known --update` as a workaround to update to PHP 7.4.1 before the phpbrew releases.

**Comment by njt1982** [comment] 2020-01-17 12:18
I had this error again but doing a `phpbrew self-update` fixed it. It updated from 1.24.1 to 1.25.3 and update works now.

**Comment by iamxie1127** [comment] 2020-03-31 05:36
I had this error, when run `phpbrew  update` . phpbrew 1.26.0
