### ISSUE TITLE
Unable to use "phpbrew known" directive after installing PHP 7.2.5

### ISSUE THREAD

**Issue by OCDpunk** [phpbrew/phpbrew#970] opened 2018-05-19 22:11 UTC
System: macOS10.13.4

Unable to use "phpbrew known" directive after installing PHP 7.2.5

Will report the following error:

# WARNING: json extension is required for parsing release info.
# WARNING: ctype extension might be required for parsing yaml file.
Read local release list (last update: 2018-05-19 21:31:07 UTC).
PHP Fatal error: Uncaught Error: Call to undefined function PhpBrew\json_decode() in phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php:50
Stack trace:
#0 phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php(61): PhpBrew\ReleaseList->loadJson('{\n "7.2": {\n...')
#1 phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php(119): PhpBrew\ReleaseList->loadJsonFile('/Users/ocdpunk/...')
#2 phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/KnownCommand.php(41): PhpBrew\ReleaseList->loadLocalReleaseList()
#3 [internal function]: PhpBrew\Command\KnownCommand->execute()
#4 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php(846): call_user_func_array(Array, Array)
#5 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php(398): CLIFramework\CommandBase->executeWrapper(Array)
#6 phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php(114): CLIFramework\Application->run(Array)
#7 phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php(2): PhpBrew\Console->runWithTry(Array) in phar:///usr/local/bin/phpbrew/src /PhpBrew/ReleaseList.php on line 50

Fatal error: Uncaught Error: Call to undefined function PhpBrew\json_decode() in phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php:50
Stack trace:
#0 phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php(61): PhpBrew\ReleaseList->loadJson('{\n "7.2": {\n...')
#1 phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php(119): PhpBrew\ReleaseList->loadJsonFile('/Users/ocdpunk/...')
#2 phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/KnownCommand.php(41): PhpBrew\ReleaseList->loadLocalReleaseList()
#3 [internal function]: PhpBrew\Command\KnownCommand->execute()
#4 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php(846): call_user_func_array(Array, Array)
#5 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php(398): CLIFramework\CommandBase->executeWrapper(Array)
#6 phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php(114): CLIFramework\Application->run(Array)
#7 phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php(2): PhpBrew\Console->runWithTry(Array) in phar:///usr/local/bin/phpbrew/src /PhpBrew/ReleaseList.php on line 50

**Comment by iChwn** [comment] 2018-10-11 04:15
same issues

**Comment by miracle666666** [comment] 2018-11-09 06:31
## command

`phpbrew known`

## platform

`System: 10.14.1`

## output

```bash
# WARNING: json extension is required for parsing release info.
# WARNING: ctype extension might be required for parsing yaml file.
Read local release list 
PHP Fatal error:  Uncaught Error: Call to undefined function PhpBrew\json_decode() in phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php:50
Stack trace:
#0 phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php(61): PhpBrew\ReleaseList->loadJson('{\n    "7.2": {\n...')
#1 phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php(119): PhpBrew\ReleaseList->loadJsonFile('/Users/....')
#2 phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/KnownCommand.php(41): PhpBrew\ReleaseList->loadLocalReleaseList()
#3 [internal function]: PhpBrew\Command\KnownCommand->execute()
#4 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php(846): call_user_func_array(Array, Array)
#5 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php(398): CLIFramework\CommandBase->executeWrapper(Array)
#6 phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php(114): CLIFramework\Application->run(Array)
#7 phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php(2): PhpBrew\Console->runWithTry(Array) in phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php on line 50

Fatal error: Uncaught Error: Call to undefined function PhpBrew\json_decode() in phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php:50
Stack trace:
#0 phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php(61): PhpBrew\ReleaseList->loadJson('{\n    "7.2": {\n...')
#1 phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php(119): PhpBrew\ReleaseList->loadJsonFile('/Users/....')
#2 phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/KnownCommand.php(41): PhpBrew\ReleaseList->loadLocalReleaseList()
#3 [internal function]: PhpBrew\Command\KnownCommand->execute()
#4 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php(846): call_user_func_array(Array, Array)
#5 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php(398): CLIFramework\CommandBase->executeWrapper(Array)
#6 phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php(114): CLIFramework\Application->run(Array)
#7 phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php(2): PhpBrew\Console->runWithTry(Array) in phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php on line 50
```

Did that mean I need to install json support with `brew install`?

**Comment by morozov** [comment] 2020-01-02 20:47
The `json` extension was obviously missing. Closing as by design.

**Closed by morozov** 2020-01-02 20:47 UTC
