### ISSUE TITLE
phpbrew prepends $PATH on every cd command

### ISSUE THREAD

**Issue by larsnystrom** [phpbrew/phpbrew#487] opened 2015-04-20 07:36 UTC
I believe PR #391 introduced a bug which causes `$PATH` to be prepended with the path to the current php version every time you run `cd`. Example output from my terminal:

	lars@lars-zb-ubuntu:~$ echo $PATH
	/home/lars/.phpbrew/php/php-5.5.24/bin:/home/lars/.phpbrew/php/php-5.5.24/bin:/usr/local/heroku/bin:/home/lars/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/go/bin:/home/lars/.go/bin
	lars@lars-zb-ubuntu:~$ cd ..
	lars@lars-zb-ubuntu:/home$ echo $PATH
	/home/lars/.phpbrew/php/php-5.5.24/bin:/home/lars/.phpbrew/php/php-5.5.24/bin:/home/lars/.phpbrew/php/php-5.5.24/bin:/usr/local/heroku/bin:/home/lars/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/go/bin:/home/lars/.go/bin
	lars@lars-zb-ubuntu:/home$ cd
	lars@lars-zb-ubuntu:~$ echo $PATH
	/home/lars/.phpbrew/php/php-5.5.24/bin:/home/lars/.phpbrew/php/php-5.5.24/bin:/home/lars/.phpbrew/php/php-5.5.24/bin:/home/lars/.phpbrew/php/php-5.5.24/bin:/usr/local/heroku/bin:/home/lars/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/go/bin:/home/lars/.go/bin

The path is also prepended twice when you start a new shell.

We should use `sed` or something else to replace the current path instead of just prepending the path all the time.

**Comment by marcioAlmada** [comment] 2015-05-07 23:39
confirmed cc @morozov

**Comment by morozov** [comment] 2015-05-08 07:23
I'll take a look at this probably next week.

**Comment by morozov** [comment] 2015-05-13 05:56
@larsnystrom I couldn't reproduce the case when the same path is prepended more than once, but I was able to get multiple different phpbrew paths in `$PATH` when switching between projects. Please see if https://github.com/phpbrew/phpbrew/pull/500 solves your problem. Otherwise, please tell us where your `.phpbrewrc` files are located and what their content is. With the patched `bashrc`, I'm getting the following results:
```
morozov@viola:~
↪  echo $PATH
/home/morozov/.phpbrew/php/php-5.6.8/bin:/home/morozov/.phpbrew/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
morozov@viola:~
↪  cd Mango/
morozov@viola:~/Mango
↪  echo $PATH
/home/morozov/.phpbrew/php/php-5.3.29/bin:/home/morozov/.phpbrew/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
morozov@viola:~/Mango
↪  cd
morozov@viola:~
↪  echo $PATH
/home/morozov/.phpbrew/php/php-5.6.8/bin:/home/morozov/.phpbrew/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Comment by marcioAlmada** [comment] 2015-05-13 22:42
@morozov  Thanks. I'll test your PR tomorrow.

**Comment by larsnystrom** [comment] 2015-05-15 10:36
PR #500 fixes my issue.

**Comment by marcioAlmada** [comment] 2015-05-15 21:42
This will be fixed on next minor release. Thank you.

**Closed by marcioAlmada** 2015-05-15 21:42 UTC
Labels: Bug
