### ISSUE TITLE
Enabled package when +package added to building process

### ISSUE THREAD

**Issue by markwu** [phpbrew/phpbrew#761] opened 2016-06-15 04:32 UTC
When I used the command to build php-7.0.6

`phpbrew --debug install php-7.0.6`

I did not set any variants, the default variant will be used. 

The following packages will be compiled 

```
Checking patch for replace apache php module name with custom version name
Enabled variants: [bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, pcntl, pcre, pdo, phar, posix, readline, sockets, tokenizer, xml, curl, zip, openssl, opcache, mcrypt]
Disabled variants: []
```

After the installation, I try to get compile/module information form `php -i` and `php-m`, I found the `opcache` does not enabled by default, although it compiled by default.

I need to create .phpbrew/var/db, and place a opcache.ini with correct setting to enable it. Because I can't use `phpbrew ext enable opcache` to enable it. it just tell me

```
===> Enabling extension opcache
opcache extension is not installed. Suggestions:
    $ phpbrew ext install opcache
```

Is it the expecated behavior?

I suppose phpbrew should handle these extensions for users. 

My environment is 

`OSX 10.11.4 & homebrew & PHP-7.0.7`

The same issue happend in `+gd` variants, maybe others.

**Comment by c9s** [comment] 2016-06-15 08:13
The config depends on the php build system. However, I think the extension enable/disable commands need to be improved.

**Comment by c9s** [comment] 2016-06-15 08:13
Can you run php --ri "Zend OPcache" ?

**Comment by markwu** [comment] 2016-06-15 15:09
Here comes the result

```
$ php --ri "Zend OPcache"
Extension 'Zend OPcache' not present.
```

**Comment by morozov** [comment] 2017-10-25 17:35
> Is it the expected behavior?

By the moment, yes. Currently, PHPBrew does not support automatic enablement of shared extensions. Opcache is one of those which can be [only compiled as shared](http://php.net/manual/en/opcache.installation.php#opcache.installation.bundled):

> OPcache can only be compiled as a shared extension.

Starting PHPBrew 1.23, manual execution of `phpbrew ext install opcache` and `phpbrew ext install gd` will enable them (the "opcache extension is not installed" error should be now gone).

**Comment by peter279k** [comment] 2022-12-02 08:29
The issue is outdated and resolved in the previous reply. Closed.

**Closed by peter279k** 2022-12-02 08:29 UTC
Labels: Extension Installer
