### ISSUE TITLE
Warning:: command not found (some error in bashrc)

### ISSUE THREAD

**Issue by netandreus** [phpbrew/phpbrew#694] opened 2016-03-22 12:27 UTC
After I added this lines to my .bashrc
source /opt/phpbrew/.phpbrew/bashrc
like in Installating manual and relogin I've got this error:
Warning:: command not found
when login to ssh

OS: Ubuntu 15.04

**Comment by c9s** [comment] 2016-03-22 12:38
Can you gist your env?

    $ env

**Comment by netandreus** [comment] 2016-03-22 12:46
yes, here it is

phpbrew@web1:~$ env
LC_PAPER=ru_RU.UTF-8
XDG_SESSION_ID=37
LC_ADDRESS=ru_RU.UTF-8
LC_MONETARY=ru_RU.UTF-8
PHPBREW_BIN=/opt/phpbrew/.phpbrew/bin
PHPBREW_PATH=/opt/phpbrew/.phpbrew/php/php-7.0.4/bin
TERM=xterm
SHELL=/bin/bash
SSH_CLIENT=62.117.122.51 53133 22
PHPBREW_ROOT=/opt/phpbrew/.phpbrew
LC_NUMERIC=ru_RU.UTF-8
SSH_TTY=/dev/pts/0
USER=phpbrew
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
LC_TELEPHONE=ru_RU.UTF-8
MAIL=/var/mail/phpbrew
PATH=/opt/phpbrew/.phpbrew/php/php-7.0.4/bin:/opt/phpbrew/.phpbrew/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PHPBREW_HOME=/opt/phpbrew/.phpbrew
LC_IDENTIFICATION=ru_RU.UTF-8
PHPBREW_VERSION_REGEX=^([[:digit:]]+\.){2}[[:digit:]]+$
PWD=/opt/phpbrew
PHPBREW_LOOKUP_PREFIX=
LANG=en_US.UTF-8
PATH_WITHOUT_PHPBREW=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
LC_MEASUREMENT=ru_RU.UTF-8
SHLVL=1
HOME=/opt/phpbrew
LANGUAGE=en_US:en
LOGNAME=phpbrew
SSH_CONNECTION=62.117.122.51 53133 192.168.0.11 22
LESSOPEN=| /usr/bin/lesspipe %s
PHPBREW_PHP=php-7.0.4
XDG_RUNTIME_DIR=/run/user/1001
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_TIME=ru_RU.UTF-8
LC_NAME=ru_RU.UTF-8
_=/usr/bin/env

**Comment by indiealexh** [comment] 2016-04-14 08:39
Similar issue, Source the phpbrew bashrc and terminal has no idea where to find commands.

**Comment by c9s** [comment] 2016-04-20 08:30
This is really weird. not sure what kind of the command it's looking for.

**Comment by c9s** [comment] 2016-04-20 08:37
Hi @netandreus, @indiealexh

Please help us verify this fix when you have some time to try the fix. :) It should be fixed in 86672c0e507b595c9b97bbaf7b24e38954ddf739

You can simply run `phpbrew self-update`

**Comment by c9s** [comment] 2016-04-20 08:49
I think this is really weird, I created a new aws instance with ubuntu 15.04, installed phpbrew requirements and then install phpbrew, I didn't see any "command not found" related message

**Comment by giusilvano** [comment] 2016-06-23 07:54
I had the same issue, and I successfully solved it.

My last operations with phpbrew:
* failed attempt to install php 5.2 on ubuntu 14.04 LTS
* some attempts to enable and install the `pdo_mysql` extension.
* `phpbrew clean php-5.4.45` and then `phpbrew install 5.4 +default +mysql +pdo +debug`
* `phpbrew clean php-7.0.7` and then `phpbrew install 7.0 +default +mysql +pdo +debug`

After these, this is the content of my `~/.phpbrew/init`:
    
```
# DO NOT EDIT THIS FILE

Warning: Module 'pdo_mysql' already loaded in Unknown on line 0
export PHPBREW_ROOT=/home/me/.phpbrew
export PHPBREW_HOME=/home/me/.phpbrew
export PHPBREW_LOOKUP_PREFIX=
export PHPBREW_PHP=php-5.4.45
export PHPBREW_PATH=/home/me/.phpbrew/php/php-5.4.45/bin
# Run this command to configure your shell:
# # eval "$(phpbrew env)"
```

**The problem was the 3rd line.** Removing it everything works.

**Comment by YamiOdymel** [comment] 2016-07-20 09:38
Have the same issue, and I type `sudo vi ~/.phpbrew/init` **found the PHP error messages were recorded in it**

<img width="1150" alt="2016-07-20 5 35 25" src="https://cloud.githubusercontent.com/assets/7308718/16982060/727d0354-4ea0-11e6-8509-f59c473367d9.png">

I remove them and works fine .

**Comment by jhdxr** [comment] 2016-07-20 19:05
it seems to be a duplicate of #742 , and @c9s already fix it in 81d1c97f1228d58eb3725a3f75530a7b0c9463d1

@YamiOdymel what's your phpbrew version?

**Comment by YamiOdymel** [comment] 2016-07-20 19:44
1.21.3, the latest one, I installed that last week.

**Comment by n4huel** [comment] 2016-11-30 02:09
Still happening in phpbrew 1.22.6. https://github.com/phpbrew/phpbrew/issues/694#issuecomment-227976409 is a temporal workaround.

**Comment by jhdxr** [comment] 2016-11-30 18:20
@n4huel , could you paste your origin `/opt/phpbrew/.phpbrew/bashrc` here?

**Comment by morozov** [comment] 2020-01-08 17:26
Closing due to lack of feedback.

**Closed by morozov** 2020-01-08 17:26 UTC
Labels: Bug, Need More Info
